"""ODI player styles and roles."""

STYLE_RIGHT_PACE = '⚡ Right-Arm Fast/Med'
STYLE_LEFT_PACE = '⚡ Left-Arm Fast/Med'
STYLE_OFF_SPIN = '🌀 Off Spin'
STYLE_SLA = '🌀 Slow Left-Arm Orth'
STYLE_LEG_SPIN = '🌀 Leg Spin'
STYLE_LEFT_UNORTHODOX = '🌀 Left-Arm Unorthodox'

ROLE_BATTER = 'Batter'
ROLE_BOWLER = 'Bowler'
ROLE_BAT_AR = 'Batting All-Rounder'
ROLE_BOWL_AR = 'Bowling All-Rounder'

BOWLER_STYLES = {'MA Starc': '⚡ Left-Arm Fast/Med',
 'JR Hazlewood': '⚡ Right-Arm Fast/Med',
 'PJ Cummins': '⚡ Right-Arm Fast/Med',
 'JA Richardson': '⚡ Right-Arm Fast/Med',
 'Sean Abbott': '⚡ Right-Arm Fast/Med',
 'SA Abbott': '⚡ Right-Arm Fast/Med',
 'NT Ellis': '⚡ Right-Arm Fast/Med',
 'XC Bartlett': '⚡ Right-Arm Fast/Med',
 'C Green': '⚡ Right-Arm Fast/Med',
 'MR Marsh': '⚡ Right-Arm Fast/Med',
 'MP Stoinis': '⚡ Right-Arm Fast/Med',
 'A Zampa': '🌀 Leg Spin',
 'NM Lyon': '🌀 Off Spin',
 'GJ Maxwell': '🌀 Off Spin',
 'AC Agar': '🌀 Slow Left-Arm Orth',
 'AJ Finch': '🌀 Slow Left-Arm Orth',
 'AJ Turner': '🌀 Off Spin',
 'AJ Tye': '⚡ Right-Arm Fast/Med',
 'AM Hardie': '⚡ Right-Arm Fast/Med',
 'B Stanlake': '⚡ Right-Arm Fast/Med',
 'BJ Dwarshuis': '⚡ Left-Arm Fast/Med',
 'C Connolly': '🌀 Slow Left-Arm Orth',
 'CP Tremain': '⚡ Right-Arm Fast/Med',
 'DJ Worrall': '⚡ Right-Arm Fast/Med',
 'DJM Short': '🌀 Left-Arm Unorthodox',
 'JM Mennie': '⚡ Right-Arm Fast/Med',
 'JP Behrendorff': '⚡ Left-Arm Fast/Med',
 'JP Faulkner': '⚡ Left-Arm Fast/Med',
 'JW Hastings': '⚡ Right-Arm Fast/Med',
 'KW Richardson': '⚡ Right-Arm Fast/Med',
 'LR Morris': '⚡ Right-Arm Fast/Med',
 'M Labuschagne': '🌀 Leg Spin',
 'MC Henriques': '⚡ Right-Arm Fast/Med',
 'MG Neser': '⚡ Right-Arm Fast/Med',
 'MJ Swepson': '🌀 Leg Spin',
 'MP Kuhnemann': '🌀 Slow Left-Arm Orth',
 'MW Short': '🌀 Off Spin',
 'NM Coulter-Nile': '⚡ Right-Arm Fast/Med',
 'PM Siddle': '⚡ Right-Arm Fast/Med',
 'RP Meredith': '⚡ Right-Arm Fast/Med',
 'SH Johnson': '⚡ Left-Arm Fast/Med',
 'SM Boland': '⚡ Right-Arm Fast/Med',
 'SPD Smith': '🌀 Leg Spin',
 'T Sangha': '🌀 Leg Spin',
 'TH David': '🌀 Off Spin',
 'TM Head': '🌀 Off Spin',
 'W Sutherland': '⚡ Right-Arm Fast/Med',
 'WA Agar': '⚡ Left-Arm Fast/Med',
 'JJ Bumrah': '⚡ Right-Arm Fast/Med',
 'Mohammed Shami': '⚡ Right-Arm Fast/Med',
 'Mohammed Siraj': '⚡ Right-Arm Fast/Med',
 'Harshit Rana': '⚡ Right-Arm Fast/Med',
 'M Prasidh Krishna': '⚡ Right-Arm Fast/Med',
 'HH Pandya': '⚡ Right-Arm Fast/Med',
 'Shardul Thakur': '⚡ Right-Arm Fast/Med',
 'Nithish Kumar Reddy': '⚡ Right-Arm Fast/Med',
 'Arshdeep Singh': '⚡ Left-Arm Fast/Med',
 'R Ashwin': '🌀 Off Spin',
 'Washington Sundar': '🌀 Off Spin',
 'RA Jadeja': '🌀 Slow Left-Arm Orth',
 'AR Patel': '🌀 Slow Left-Arm Orth',
 'Kuldeep Yadav': '🌀 Left-Arm Unorthodox',
 'Ravi Bishnoi': '🌀 Leg Spin',
 'YS Chahal': '🌀 Leg Spin',
 'A Mishra': '🌀 Leg Spin',
 'RD Chahar': '🌀 Leg Spin',
 'B Kumar': '⚡ Right-Arm Fast/Med',
 'UT Yadav': '⚡ Right-Arm Fast/Med',
 'Umran Malik': '⚡ Right-Arm Fast/Med',
 'Navdeep Saini': '⚡ Right-Arm Fast/Med',
 'T Natarajan': '⚡ Left-Arm Fast/Med',
 'KK Ahmed': '⚡ Left-Arm Fast/Med',
 'JD Unadkat': '⚡ Left-Arm Fast/Med',
 'C Sakariya': '⚡ Left-Arm Fast/Med',
 'BB Sran': '⚡ Left-Arm Fast/Med',
 'DL Chahar': '⚡ Right-Arm Fast/Med',
 'SN Thakur': '⚡ Right-Arm Fast/Med',
 'S Kaul': '⚡ Right-Arm Fast/Med',
 'Avesh Khan': '⚡ Right-Arm Fast/Med',
 'Mukesh Kumar': '⚡ Right-Arm Fast/Med',
 'KR Sen': '⚡ Right-Arm Fast/Med',
 'DS Kulkarni': '⚡ Right-Arm Fast/Med',
 'V Shankar': '⚡ Right-Arm Fast/Med',
 'VR Iyer': '⚡ Right-Arm Fast/Med',
 'S Dube': '⚡ Right-Arm Fast/Med',
 'J Yadav': '🌀 Off Spin',
 'K Gowtham': '🌀 Off Spin',
 'Shahbaz Ahmed': '🌀 Slow Left-Arm Orth',
 'KH Pandya': '🌀 Slow Left-Arm Orth',
 'Yuvraj Singh': '🌀 Slow Left-Arm Orth',
 'KM Jadhav': '🌀 Off Spin',
 'SK Raina': '🌀 Off Spin',
 'DJ Hooda': '🌀 Off Spin',
 'RG Sharma': '🌀 Off Spin',
 'V Kohli': '⚡ Right-Arm Fast/Med',
 'AT Rayudu': '🌀 Off Spin',
 'N Rana': '🌀 Off Spin',
 'R Parag': '🌀 Leg Spin',
 'Tilak Varma': '🌀 Off Spin',
 'SA Yadav': '🌀 Off Spin',
 'SS Iyer': '🌀 Leg Spin',
 'MA Agarwal': '🌀 Off Spin',
 'Shubman Gill': '🌀 Off Spin',
 'B Sai Sudharsan': '🌀 Leg Spin',
 'RK Singh': '🌀 Off Spin',
 'CV Varun': '🌀 Leg Spin',
 'J Archer': '⚡ Right-Arm Fast/Med',
 'MA Wood': '⚡ Right-Arm Fast/Med',
 'O Stone': '⚡ Right-Arm Fast/Med',
 'BA Carse': '⚡ Right-Arm Fast/Med',
 'G Atkinson': '⚡ Right-Arm Fast/Med',
 'AAP Atkinson': '⚡ Right-Arm Fast/Med',
 'CR Woakes': '⚡ Right-Arm Fast/Med',
 'S Mahmood': '⚡ Right-Arm Fast/Med',
 'SM Curran': '⚡ Left-Arm Fast/Med',
 'RJW Topley': '⚡ Left-Arm Fast/Med',
 'L Wood': '⚡ Left-Arm Fast/Med',
 'AU Rashid': '🌀 Leg Spin',
 'Rehan Ahmed': '🌀 Leg Spin',
 'MM Ali': '🌀 Off Spin',
 'LS Livingstone': '🌀 Off Spin',
 'W Jacks': '🌀 Off Spin',
 'WG Jacks': '🌀 Off Spin',
 'LA Dawson': '🌀 Slow Left-Arm Orth',
 'J Overton': '⚡ Right-Arm Fast/Med',
 'JG Bethell': '🌀 Slow Left-Arm Orth',
 'JE Root': '🌀 Off Spin',
 'BA Stokes': '⚡ Right-Arm Fast/Med',
 'C Overton': '⚡ Right-Arm Fast/Med',
 'CJ Jordan': '⚡ Right-Arm Fast/Med',
 'DA Payne': '⚡ Left-Arm Fast/Med',
 'DJ Malan': '🌀 Leg Spin',
 'DJ Willey': '⚡ Left-Arm Fast/Med',
 'DR Mousley': '🌀 Off Spin',
 'GLS Scrimshaw': '⚡ Right-Arm Fast/Med',
 'JA Turner': '⚡ Right-Arm Fast/Med',
 'JC Archer': '⚡ Right-Arm Fast/Med',
 'JL Denly': '🌀 Leg Spin',
 'JM Vince': '⚡ Right-Arm Fast/Med',
 'JT Ball': '⚡ Right-Arm Fast/Med',
 'L Gregory': '⚡ Right-Arm Fast/Med',
 'LE Plunkett': '⚡ Right-Arm Fast/Med',
 'MJ Potts': '⚡ Right-Arm Fast/Med',
 'MW Parkinson': '🌀 Leg Spin',
 'OP Stone': '⚡ Right-Arm Fast/Med',
 'S Baker': '⚡ Left-Arm Fast/Med',
 'SCJ Broad': '⚡ Right-Arm Fast/Med',
 'ST Finn': '⚡ Right-Arm Fast/Med',
 'TK Curran': '⚡ Right-Arm Fast/Med',
 'TS Roland-Jones': '⚡ Right-Arm Fast/Med',
 'TW Hartley': '🌀 Slow Left-Arm Orth',
 'K Rabada': '⚡ Right-Arm Fast/Med',
 'A Nortje': '⚡ Right-Arm Fast/Med',
 'G Coetzee': '⚡ Right-Arm Fast/Med',
 'L Ngidi': '⚡ Right-Arm Fast/Med',
 'O Baartman': '⚡ Right-Arm Fast/Med',
 'OEG Baartman': '⚡ Right-Arm Fast/Med',
 'AL Phehlukwayo': '⚡ Right-Arm Fast/Med',
 'W Mulder': '⚡ Right-Arm Fast/Med',
 'PWA Mulder': '⚡ Right-Arm Fast/Med',
 'M Jansen': '⚡ Left-Arm Fast/Med',
 'N Burger': '⚡ Left-Arm Fast/Med',
 'KA Maharaj': '🌀 Slow Left-Arm Orth',
 'BC Fortuin': '🌀 Slow Left-Arm Orth',
 'T Shamsi': '🌀 Left-Arm Unorthodox',
 'AK Markram': '🌀 Off Spin',
 'AM Phangiso': '🌀 Slow Left-Arm Orth',
 'BE Hendricks': '⚡ Left-Arm Fast/Med',
 'C Bosch': '⚡ Right-Arm Fast/Med',
 'CH Morris': '⚡ Right-Arm Fast/Med',
 'CJ Dala': '⚡ Right-Arm Fast/Med',
 'Codi Yusuf': '⚡ Right-Arm Fast/Med',
 'D Brevis': '🌀 Leg Spin',
 'D Ferreira': '🌀 Off Spin',
 'D Olivier': '⚡ Right-Arm Fast/Med',
 'D Paterson': '⚡ Right-Arm Fast/Med',
 'D Pretorius': '⚡ Right-Arm Fast/Med',
 'D Wiese': '⚡ Right-Arm Fast/Med',
 'DM Dupavillon': '⚡ Right-Arm Fast/Med',
 'DW Steyn': '⚡ Right-Arm Fast/Med',
 'E Bosch': '⚡ Right-Arm Fast/Med',
 'F Behardien': '⚡ Right-Arm Fast/Med',
 'GF Linde': '🌀 Slow Left-Arm Orth',
 'Imran Tahir': '🌀 Leg Spin',
 'JF Smith': '⚡ Right-Arm Fast/Med',
 'JP Duminy': '🌀 Off Spin',
 'JT Smuts': '🌀 Slow Left-Arm Orth',
 'KJ Abbott': '⚡ Right-Arm Fast/Med',
 'KT Maphaka': '⚡ Left-Arm Fast/Med',
 'L Sipamla': '⚡ Right-Arm Fast/Med',
 'LB Williams': '⚡ Right-Arm Fast/Med',
 'M Morkel': '⚡ Right-Arm Fast/Med',
 'M Mpongwana': '⚡ Right-Arm Fast/Med',
 'N Peter': '🌀 Leg Spin',
 'P Subrayen': '🌀 Off Spin',
 'S Muthusamy': '🌀 Slow Left-Arm Orth',
 'SSB Magala': '⚡ Right-Arm Fast/Med',
 'T Stubbs': '🌀 Off Spin',
 'WD Parnell': '⚡ Left-Arm Fast/Med',
 'TG Southee': '⚡ Right-Arm Fast/Med',
 'MJ Henry': '⚡ Right-Arm Fast/Med',
 'LH Ferguson': '⚡ Right-Arm Fast/Med',
 'AF Milne': '⚡ Right-Arm Fast/Med',
 'KA Jamieson': '⚡ Right-Arm Fast/Med',
 'BN Sears': '⚡ Right-Arm Fast/Med',
 'BV Sears': '⚡ Right-Arm Fast/Med',
 "W O'Rourke": '⚡ Right-Arm Fast/Med',
 'TA Boult': '⚡ Left-Arm Fast/Med',
 'MJ Santner': '🌀 Slow Left-Arm Orth',
 'R Ravindra': '🌀 Slow Left-Arm Orth',
 'IS Sodhi': '🌀 Leg Spin',
 'GD Phillips': '🌀 Off Spin',
 'MG Bracewell': '🌀 Off Spin',
 'DJ Mitchell': '⚡ Right-Arm Fast/Med',
 'JR Lennox': '🌀 Slow Left-Arm Orth',
 'KDC Clarke': '⚡ Right-Arm Fast/Med',
 'ZGF Foulkes': '⚡ Right-Arm Fast/Med',
 'A Ashok': '🌀 Leg Spin',
 'AP Devcich': '🌀 Slow Left-Arm Orth',
 'BG Lister': '⚡ Left-Arm Fast/Med',
 'BM Tickner': '⚡ Right-Arm Fast/Med',
 'C Munro': '⚡ Right-Arm Fast/Med',
 'C de Grandhomme': '⚡ Right-Arm Fast/Med',
 'CE McConchie': '🌀 Off Spin',
 'CJ Anderson': '⚡ Left-Arm Fast/Med',
 'DAJ Bracewell': '⚡ Right-Arm Fast/Med',
 'HB Shipley': '⚡ Right-Arm Fast/Med',
 'HK Bennett': '⚡ Right-Arm Fast/Med',
 'JA Clarkson': '⚡ Right-Arm Fast/Med',
 'JA Duffy': '⚡ Right-Arm Fast/Med',
 'JDS Neesham': '⚡ Right-Arm Fast/Med',
 'JS Patel': '🌀 Off Spin',
 'KS Williamson': '🌀 Off Spin',
 'MA Abbas': '⚡ Right-Arm Fast/Med',
 'NG Smith': '⚡ Right-Arm Fast/Med',
 'SC Kuggeleijn': '⚡ Right-Arm Fast/Med',
 'SHA Rance': '⚡ Right-Arm Fast/Med',
 'TD Astle': '🌀 Leg Spin',
 'Naseem Shah': '⚡ Right-Arm Fast/Med',
 'Haris Rauf': '⚡ Right-Arm Fast/Med',
 'Hasan Ali': '⚡ Right-Arm Fast/Med',
 'Mohammad Wasim': '⚡ Right-Arm Fast/Med',
 'Zaman Khan': '⚡ Right-Arm Fast/Med',
 'Aamer Jamal': '⚡ Right-Arm Fast/Med',
 'Faheem Ashraf': '⚡ Right-Arm Fast/Med',
 'Shaheen Shah Afridi': '⚡ Left-Arm Fast/Med',
 'Mir Hamza': '⚡ Left-Arm Fast/Med',
 'Shadab Khan': '🌀 Leg Spin',
 'Usama Mir': '🌀 Leg Spin',
 'Abrar Ahmed': '🌀 Leg Spin',
 'Mohammad Nawaz': '🌀 Slow Left-Arm Orth',
 'Mohammad Nawaz (3)': '🌀 Slow Left-Arm Orth',
 'Iftikhar Ahmed': '🌀 Off Spin',
 'Agha Salman': '🌀 Off Spin',
 'Aamer Yamin': '⚡ Right-Arm Fast/Med',
 'Akif Javed': '⚡ Left-Arm Fast/Med',
 'Asif Ali': '🌀 Off Spin',
 'Azhar Ali': '🌀 Leg Spin',
 'Danish Aziz': '🌀 Slow Left-Arm Orth',
 'Faisal Akram': '🌀 Left-Arm Unorthodox',
 'Fakhar Zaman': '🌀 Slow Left-Arm Orth',
 'Haris Sohail': '🌀 Slow Left-Arm Orth',
 'Hussain Talat': '⚡ Right-Arm Fast/Med',
 'Ihsanullah': '⚡ Right-Arm Fast/Med',
 'Imad Wasim': '🌀 Slow Left-Arm Orth',
 'Irfan Khan': '🌀 Off Spin',
 'Junaid Khan': '⚡ Left-Arm Fast/Med',
 'Kamran Ghulam': '🌀 Slow Left-Arm Orth',
 'Khushdil Shah': '🌀 Slow Left-Arm Orth',
 'Mohammad Abbas': '⚡ Right-Arm Fast/Med',
 'Mohammad Ali': '⚡ Right-Arm Fast/Med',
 'Mohammad Amir': '⚡ Left-Arm Fast/Med',
 'Mohammad Hafeez': '🌀 Off Spin',
 'Mohammad Hasnain': '⚡ Right-Arm Fast/Med',
 'Mohammad Irfan': '⚡ Left-Arm Fast/Med',
 'Muhammad Musa': '⚡ Right-Arm Fast/Med',
 'Rumman Raees': '⚡ Left-Arm Fast/Med',
 'Saim Ayub': '🌀 Off Spin',
 'Sarfraz Ahmed': '🌀 Off Spin',
 'Saud Shakeel': '🌀 Slow Left-Arm Orth',
 'Shahnawaz Dhani': '⚡ Right-Arm Fast/Med',
 'Shoaib Malik': '🌀 Off Spin',
 'Sohail Khan': '⚡ Right-Arm Fast/Med',
 'Sufiyan Muqeem': '🌀 Left-Arm Unorthodox',
 'Umar Amin': '⚡ Right-Arm Fast/Med',
 'Umar Gul': '⚡ Right-Arm Fast/Med',
 'Usman Qadir': '🌀 Leg Spin',
 'Usman Shinwari': '⚡ Left-Arm Fast/Med',
 'Wahab Riaz': '⚡ Left-Arm Fast/Med',
 'Yasir Shah': '🌀 Leg Spin',
 'Zahid Mahmood': '🌀 Leg Spin',
 'PVD Chameera': '⚡ Right-Arm Fast/Med',
 'M Pathirana': '⚡ Right-Arm Fast/Med',
 'CBRLS Kumara': '⚡ Right-Arm Fast/Med',
 'CAK Rajitha': '⚡ Right-Arm Fast/Med',
 'AM Fernando': '⚡ Right-Arm Fast/Med',
 'C Karunaratne': '⚡ Right-Arm Fast/Med',
 'N Thushara': '⚡ Right-Arm Fast/Med',
 'MD Shanaka': '⚡ Right-Arm Fast/Med',
 'D Madushanka': '⚡ Left-Arm Fast/Med',
 'PWH de Silva': '🌀 Leg Spin',
 'JDF Vandersay': '🌀 Leg Spin',
 'M Theekshana': '🌀 Off Spin',
 'DM de Silva': '🌀 Off Spin',
 'KIC Asalanka': '🌀 Off Spin',
 'DN Wellalage': '🌀 Slow Left-Arm Orth',
 'PM Liyanagamage': '⚡ Right-Arm Fast/Med',
 'K Mishara': '🌀 Off Spin',
 'J Liyanage': '⚡ Right-Arm Fast/Med',
 'A Dananjaya': '🌀 Leg Spin',
 'AD Mathews': '⚡ Right-Arm Fast/Med',
 'AK Perera': '🌀 Slow Left-Arm Orth',
 'B Fernando': '⚡ Left-Arm Fast/Med',
 'BMAJ Mendis': '🌀 Slow Left-Arm Orth',
 'BOP Fernando': '🌀 Leg Spin',
 'C Gunasekara': '🌀 Leg Spin',
 'C Wickramasinghe': '⚡ Right-Arm Fast/Med',
 'D Lakshan': '⚡ Right-Arm Fast/Med',
 'DAS Gunaratne': '⚡ Right-Arm Fast/Med',
 'DSK Madushanka': '⚡ Left-Arm Fast/Med',
 'E Malinga': '⚡ Right-Arm Fast/Med',
 'FDM Karunaratne': '⚡ Right-Arm Fast/Med',
 'GSNFG Jayasuriya': '🌀 Slow Left-Arm Orth',
 'I Udana': '⚡ Left-Arm Fast/Med',
 'KMC Bandara': '🌀 Leg Spin',
 'KMDN Kulasekara': '⚡ Right-Arm Fast/Med',
 'KNA Bandara': '🌀 Leg Spin',
 'LD Madushanka': '⚡ Right-Arm Fast/Med',
 'M Shiraz': '⚡ Right-Arm Fast/Med',
 'MA Aponso': '🌀 Slow Left-Arm Orth',
 'MADI Hemantha': '🌀 Leg Spin',
 'MD Gunathilaka': '🌀 Off Spin',
 'MDK Perera': '🌀 Off Spin',
 'MF Maharoof': '⚡ Right-Arm Fast/Med',
 'MNK Fernando': '⚡ Right-Arm Fast/Med',
 'MVT Fernando': '⚡ Left-Arm Fast/Med',
 'N Pradeep': '⚡ Right-Arm Fast/Med',
 'NGRP Jayasuriya': '🌀 Slow Left-Arm Orth',
 'NLTC Perera': '⚡ Right-Arm Fast/Med',
 'P Jayawickrama': '🌀 Slow Left-Arm Orth',
 'P Rathnayake': '⚡ Right-Arm Fast/Med',
 'PADLR Sandakan': '🌀 Left-Arm Unorthodox',
 'PC de Silva': '🌀 Off Spin',
 'PHKD Mendis': '🌀 Leg Spin',
 'PLS Gamage': '⚡ Right-Arm Fast/Med',
 'PM Pushpakumara': '🌀 Slow Left-Arm Orth',
 'RAS Lakmal': '⚡ Right-Arm Fast/Med',
 'RMMP Rathnayake': '⚡ Right-Arm Fast/Med',
 'RTM Mendis': '🌀 Off Spin',
 'S Prasanna': '🌀 Leg Spin',
 'S Randiv': '🌀 Off Spin',
 'SL Malinga': '⚡ Right-Arm Fast/Med',
 'SS Pathirana': '🌀 Slow Left-Arm Orth',
 'SSD Arachchige': '🌀 Off Spin',
 'TAM Siriwardana': '🌀 Slow Left-Arm Orth',
 'TM Dilshan': '🌀 Off Spin',
 'BKG Mendis': '🌀 Leg Spin',
 'AS Joseph': '⚡ Right-Arm Fast/Med',
 'O Thomas': '⚡ Right-Arm Fast/Med',
 'JNT Seales': '⚡ Right-Arm Fast/Med',
 'S Gabriel': '⚡ Right-Arm Fast/Med',
 'J Holder': '⚡ Right-Arm Fast/Med',
 'JO Holder': '⚡ Right-Arm Fast/Med',
 'R Shepherd': '⚡ Right-Arm Fast/Med',
 'AJ Hosein': '🌀 Slow Left-Arm Orth',
 'G Motie': '🌀 Slow Left-Arm Orth',
 'K Pierre': '🌀 Slow Left-Arm Orth',
 'RL Chase': '🌀 Off Spin',
 'JP Greaves': '🌀 Off Spin',
 'A Athanaze': '🌀 Off Spin',
 'A Phillip': '⚡ Right-Arm Fast/Med',
 'AD Russell': '⚡ Right-Arm Fast/Med',
 'AM McCarthy': '🌀 Off Spin',
 'AR Nurse': '🌀 Off Spin',
 'Akeem Jordan': '⚡ Right-Arm Fast/Med',
 'C Hemraj': '🌀 Slow Left-Arm Orth',
 'CH Gayle': '🌀 Off Spin',
 'CK Holder': '⚡ Right-Arm Fast/Med',
 'CR Brathwaite': '⚡ Right-Arm Fast/Med',
 'D Bishoo': '🌀 Leg Spin',
 'DC Drakes': '⚡ Right-Arm Fast/Med',
 'FA Allen': '🌀 Slow Left-Arm Orth',
 'HR Walsh': '🌀 Leg Spin',
 'J Blades': '🌀 Off Spin',
 'JD Campbell': '🌀 Off Spin',
 'JE Taylor': '⚡ Right-Arm Fast/Med',
 'JL Carter': '⚡ Right-Arm Fast/Med',
 'JN Mohammed': '🌀 Off Spin',
 'K Sinclair': '🌀 Off Spin',
 'KA Pollard': '⚡ Right-Arm Fast/Med',
 'KAJ Roach': '⚡ Right-Arm Fast/Med',
 'KAR Hodge': '🌀 Slow Left-Arm Orth',
 'KC Brathwaite': '🌀 Off Spin',
 'KJ Harding': '⚡ Right-Arm Fast/Med',
 'KMA Paul': '⚡ Right-Arm Fast/Med',
 'KOK Williams': '⚡ Right-Arm Fast/Med',
 'KR Mayers': '⚡ Right-Arm Fast/Med',
 'KU Carty': '⚡ Right-Arm Fast/Med',
 'MJ Mindley': '⚡ Right-Arm Fast/Med',
 'ML Cummins': '⚡ Right-Arm Fast/Med',
 'MN Samuels': '🌀 Off Spin',
 'MW Forde': '⚡ Right-Arm Fast/Med',
 'NO Miller': '🌀 Slow Left-Arm Orth',
 'OC McCoy': '⚡ Left-Arm Fast/Med',
 'OF Smith': '⚡ Right-Arm Fast/Med',
 'R Powell': '⚡ Right-Arm Fast/Med',
 'RA Reifer': '⚡ Left-Arm Fast/Med',
 'RR Beaton': '⚡ Right-Arm Fast/Med',
 'S Joseph': '⚡ Right-Arm Fast/Med',
 'SE Rutherford': '⚡ Right-Arm Fast/Med',
 'SH Lewis': '⚡ Right-Arm Fast/Med',
 'SJ Benn': '🌀 Slow Left-Arm Orth',
 'SK Springer': '⚡ Right-Arm Fast/Med',
 'SP Narine': '🌀 Off Spin',
 'SS Cottrell': '⚡ Left-Arm Fast/Med',
 'ST Gabriel': '⚡ Right-Arm Fast/Med',
 'V Permaul': '🌀 Slow Left-Arm Orth',
 'Y Cariah': '🌀 Leg Spin',
 'Taskin Ahmed': '⚡ Right-Arm Fast/Med',
 'Hasan Mahmud': '⚡ Right-Arm Fast/Med',
 'Ebadot Hossain': '⚡ Right-Arm Fast/Med',
 'Tanzim Hasan Sakib': '⚡ Right-Arm Fast/Med',
 'Mustafizur Rahman': '⚡ Left-Arm Fast/Med',
 'Shoriful Islam': '⚡ Left-Arm Fast/Med',
 'Shakib Al Hasan': '🌀 Slow Left-Arm Orth',
 'Nasum Ahmed': '🌀 Slow Left-Arm Orth',
 'Taijul Islam': '🌀 Slow Left-Arm Orth',
 'Mehedi Hasan Miraz': '🌀 Off Spin',
 'Rishad Hossain': '🌀 Leg Spin',
 'Afif Hossain': '🌀 Off Spin',
 'Mahmudullah': '🌀 Off Spin',
 'Mahedi Hasan': '🌀 Off Spin',
 'Mashrafe Mortaza': '⚡ Right-Arm Fast/Med',
 'Mehidy Hasan Miraz': '🌀 Off Spin',
 'Mohammad Saifuddin': '⚡ Right-Arm Fast/Med',
 'Mosaddek Hossain': '🌀 Off Spin',
 'Nayeem Hasan': '🌀 Off Spin',
 'Rubel Hossain': '⚡ Right-Arm Fast/Med',
 'Soumya Sarkar': '⚡ Right-Arm Fast/Med',
 'Sunzamul Islam': '🌀 Slow Left-Arm Orth',
 'B Muzarabani': '⚡ Right-Arm Fast/Med',
 'TL Chatara': '⚡ Right-Arm Fast/Med',
 'R Ngarava': '⚡ Left-Arm Fast/Med',
 'LM Jongwe': '⚡ Right-Arm Fast/Med',
 'DT Tiripano': '⚡ Right-Arm Fast/Med',
 'SC Williams': '🌀 Slow Left-Arm Orth',
 'R Burl': '🌀 Leg Spin',
 'Sikandar Raza': '🌀 Off Spin',
 'WP Masakadza': '🌀 Slow Left-Arm Orth',
 'A Ndlovu': '🌀 Slow Left-Arm Orth',
 'B Evans': '⚡ Right-Arm Fast/Med',
 'CJ Chibhabha': '⚡ Right-Arm Fast/Med',
 'CT Mumba': '⚡ Right-Arm Fast/Med',
 'F Akram': '⚡ Left-Arm Fast/Med',
 'H Masakadza': '🌀 Slow Left-Arm Orth',
 'Innocent Kaia': '🌀 Leg Spin',
 'KM Jarvis': '⚡ Right-Arm Fast/Med',
 'M Shumba': '🌀 Slow Left-Arm Orth',
 'N Madziva': '⚡ Right-Arm Fast/Med',
 'T Maruma': '🌀 Leg Spin',
 'TS Chisoro': '🌀 Slow Left-Arm Orth',
 'MR Adair': '⚡ Right-Arm Fast/Med',
 'CA Young': '⚡ Right-Arm Fast/Med',
 'B McCarthy': '⚡ Right-Arm Fast/Med',
 'AR McBrine': '🌀 Off Spin',
 'GH Dockrell': '🌀 Slow Left-Arm Orth',
 'GJ Delany': '🌀 Leg Spin',
 'SC Getkate': '⚡ Right-Arm Fast/Med',
 'Joshua Little': '⚡ Left-Arm Fast/Med',
 'C Campher': '⚡ Right-Arm Fast/Med',
 'F Hand': '⚡ Right-Arm Fast/Med',
 'G Hume': '⚡ Right-Arm Fast/Med',
 'Harry Tector': '🌀 Off Spin',
 'Simi Singh': '🌀 Off Spin',
 'WB Rankin': '⚡ Right-Arm Fast/Med',
 'Logan van Beek': '⚡ Right-Arm Fast/Med',
 'Paul van Meekeren': '⚡ Right-Arm Fast/Med',
 'Bas de Leede': '⚡ Right-Arm Fast/Med',
 'Aryan Dutt': '🌀 Off Spin',
 'Roelof van der Merwe': '🌀 Slow Left-Arm Orth',
 'Shariz Ahmad': '🌀 Leg Spin',
 'Fred Klaassen': '⚡ Left-Arm Fast/Med',
 'Ryan Klein': '⚡ Right-Arm Fast/Med',
 'Vivian Kingma': '⚡ Right-Arm Fast/Med',
 'Tim Pringle': '🌀 Slow Left-Arm Orth',
 'Brandon Glover': '⚡ Right-Arm Fast/Med',
 'Sikander Zulfiqar': '⚡ Right-Arm Fast/Med',
 'Sybrand Engelbrecht': '🌀 Off Spin',
 'B Lee': '⚡ Right-Arm Fast/Med',
 'JM Anderson': '⚡ Right-Arm Fast/Med',
 'Shahid Afridi': '🌀 Leg Spin',
 'MG Johnson': '⚡ Left-Arm Fast/Med',
 'Z Khan': '⚡ Left-Arm Fast/Med',
 'M Muralitharan': '🌀 Off Spin',
 'DL Vettori': '🌀 Slow Left-Arm Orth',
 'KD Mills': '⚡ Right-Arm Fast/Med',
 'DJ Bravo': '⚡ Right-Arm Fast/Med',
 'Harbhajan Singh': '🌀 Off Spin',
 'Saeed Ajmal': '🌀 Off Spin',
 'Abdur Razzak': '🌀 Slow Left-Arm Orth',
 'NW Bracken': '⚡ Left-Arm Fast/Med',
 'SR Watson': '⚡ Right-Arm Fast/Med',
 'IK Pathan': '⚡ Left-Arm Fast/Med',
 'M Ntini': '⚡ Right-Arm Fast/Med',
 'BAW Mendis': '🌀 Off Spin',
 'GB Hogg': '🌀 Left-Arm Unorthodox',
 'A Flintoff': '⚡ Right-Arm Fast/Med',
 'JDP Oram': '⚡ Right-Arm Fast/Med',
 'I Sharma': '⚡ Right-Arm Fast/Med',
 'WPUJC Vaas': '⚡ Left-Arm Fast/Med',
 'SM Pollock': '⚡ Right-Arm Fast/Med',
 'TT Bresnan': '⚡ Right-Arm Fast/Med',
 'CRD Fernando': '⚡ Right-Arm Fast/Med',
 'A Nehra': '⚡ Left-Arm Fast/Med',
 'R Rampaul': '⚡ Right-Arm Fast/Med',
 'SE Bond': '⚡ Right-Arm Fast/Med',
 'Abdul Razzaq': '⚡ Right-Arm Fast/Med',
 'GD McGrath': '⚡ Right-Arm Fast/Med',
 'GP Swann': '🌀 Off Spin',
 'AB Agarkar': '⚡ Right-Arm Fast/Med',
 'ST Jayasuriya': '🌀 Slow Left-Arm Orth',
 'CJ McKay': '⚡ Right-Arm Fast/Med',
 'P Utseya': '🌀 Off Spin',
 'Shoaib Akhtar': '⚡ Right-Arm Fast/Med',
 'JH Kallis': '⚡ Right-Arm Fast/Med',
 'SM Sharif': '⚡ Right-Arm Fast/Med',
 'LL Tsotsobe': '⚡ Left-Arm Fast/Med',
 'Naved-ul-Hasan': '⚡ Right-Arm Fast/Med',
 'PD Collingwood': '⚡ Right-Arm Fast/Med',
 'A Nel': '⚡ Right-Arm Fast/Med',
 'MM Patel': '⚡ Right-Arm Fast/Med',
 'Junaid Siddique': '⚡ Right-Arm Fast/Med',
 'MJ McClenaghan': '⚡ Left-Arm Fast/Med',
 'E Chigumbura': '⚡ Right-Arm Fast/Med',
 'CK Langeveldt': '⚡ Right-Arm Fast/Med',
 'DJG Sammy': '⚡ Right-Arm Fast/Med',
 'RW Price': '🌀 Slow Left-Arm Orth',
 'P Kumar': '⚡ Right-Arm Fast/Med',
 'AJ Hall': '⚡ Right-Arm Fast/Med',
 'R McLaren': '⚡ Right-Arm Fast/Med',
 'A Symonds': '🌀 Off Spin',
 'S Sreesanth': '⚡ Right-Arm Fast/Med',
 'HMRKB Herath': '🌀 Slow Left-Arm Orth',
 'J Botha': '🌀 Off Spin',
 'SB Styris': '⚡ Right-Arm Fast/Med',
 'RJ Peterson': '🌀 Slow Left-Arm Orth',
 'AG Cremer': '🌀 Leg Spin',
 'Sohail Tanvir': '⚡ Left-Arm Fast/Med',
 'RP Singh': '⚡ Left-Arm Fast/Med',
 'JR Hopes': '⚡ Right-Arm Fast/Med',
 'Shafiul Islam': '⚡ Right-Arm Fast/Med',
 'Iftikhar Anjum': '⚡ Right-Arm Fast/Med',
 'Mohammad Sami': '⚡ Right-Arm Fast/Med',
 'NL McCullum': '🌀 Off Spin',
 'IDR Bradshaw': '⚡ Left-Arm Fast/Med',
 'CB Mpofu': '⚡ Right-Arm Fast/Med',
 'SJ Harmison': '⚡ Right-Arm Fast/Med',
 'SW Tait': '⚡ Right-Arm Fast/Med',
 'DE Bollinger': '⚡ Left-Arm Fast/Med',
 'XJ Doherty': '🌀 Slow Left-Arm Orth',
 'JC Tredwell': '🌀 Off Spin',
 "KJ O'Brien": '⚡ Right-Arm Fast/Med',
 'T Panyangara': '⚡ Right-Arm Fast/Med',
 'SMSM Senanayake': '🌀 Off Spin',
 'JN Gillespie': '⚡ Right-Arm Fast/Med',
 'V Sehwag': '🌀 Off Spin',
 'JEC Franklin': '⚡ Left-Arm Fast/Med',
 'D Gough': '⚡ Right-Arm Fast/Med',
 'MJ Clarke': '🌀 Slow Left-Arm Orth',
 'NM Hauritz': '🌀 Off Spin',
 'Mohammad Rafique': '🌀 Slow Left-Arm Orth',
 'DR Smith': '⚡ Right-Arm Fast/Med',
 'FH Edwards': '⚡ Right-Arm Fast/Med',
 'Syed Rasel': '⚡ Left-Arm Fast/Med',
 'DBL Powell': '⚡ Right-Arm Fast/Med',
 'DR Tuffey': '⚡ Right-Arm Fast/Med',
 'SR Clark': '⚡ Right-Arm Fast/Med',
 'JA Morkel': '⚡ Right-Arm Fast/Med',
 'T Thushara': '⚡ Left-Arm Fast/Med',
 'TJ Murtagh': '⚡ Right-Arm Fast/Med',
 'RE van der Merwe': '🌀 Slow Left-Arm Orth',
 'R Vinay Kumar': '⚡ Right-Arm Fast/Med',
 'RJ Harris': '⚡ Right-Arm Fast/Med',
 'TM Odoyo': '⚡ Right-Arm Fast/Med',
 'HH Streak': '⚡ Right-Arm Fast/Med',
 'VD Philander': '⚡ Right-Arm Fast/Med',
 'RS Bopara': '⚡ Right-Arm Fast/Med',
 'SK Warne': '🌀 Leg Spin',
 'AF Giles': '🌀 Slow Left-Arm Orth',
 'Mohammad Asif': '⚡ Right-Arm Fast/Med',
 'DT Johnston': '⚡ Right-Arm Fast/Med',
 'T Mupariwa': '⚡ Right-Arm Fast/Med',
 'GD Elliott': '⚡ Right-Arm Fast/Med',
 'UDU Chandana': '🌀 Leg Spin',
 'SI Mahmood': '⚡ Right-Arm Fast/Med',
 'YK Pathan': '🌀 Off Spin',
 'JF Mooney': '⚡ Right-Arm Fast/Med',
 'MS Kasprowicz': '⚡ Right-Arm Fast/Med',
 'TL Best': '⚡ Right-Arm Fast/Med',
 'CD Collymore': '⚡ Right-Arm Fast/Med',
 'Abdur Rehman': '🌀 Slow Left-Arm Orth',
 'Naeem Islam': '🌀 Off Spin',
 'PJ Ongondo': '⚡ Right-Arm Fast/Med',
 'AR Cusack': '⚡ Right-Arm Fast/Med',
 'MM Sharma': '⚡ Right-Arm Fast/Med',
 'BA Williams': '⚡ Right-Arm Fast/Med',
 'RR Powar': '🌀 Off Spin',
 'AJ Bichel': '⚡ Right-Arm Fast/Med',
 'BW Hilfenhaus': '⚡ Right-Arm Fast/Med',
 'PP Chawla': '🌀 Leg Spin',
 'BV Vitori': '⚡ Left-Arm Fast/Med',
 'DT Hondo': '⚡ Right-Arm Fast/Med',
 'A Kumble': '🌀 Leg Spin',
 'J Theron': '⚡ Right-Arm Fast/Med',
 'SR Tendulkar': '🌀 Off Spin',
 'MR Gillespie': '⚡ Right-Arm Fast/Med',
 'JW Dernbach': '⚡ Right-Arm Fast/Med',
 'KTGD Prasad': '⚡ Right-Arm Fast/Med',
 'AM Blignaut': '⚡ Left-Arm Fast/Med',
 'MS Panesar': '🌀 Slow Left-Arm Orth',
 'Nazmul Hossain': '⚡ Right-Arm Fast/Med',
 'HMCM Bandara': '🌀 Leg Spin',
 'M Kartik': '🌀 Slow Left-Arm Orth',
 'IJ Harvey': '⚡ Right-Arm Fast/Med',
 'Shahadat Hossain': '⚡ Right-Arm Fast/Med',
 'SO Tikolo': '🌀 Off Spin',
 'Tapash Baisya': '⚡ Right-Arm Fast/Med',
 'L Balaji': '⚡ Right-Arm Fast/Med',
 'AJ McKay': '⚡ Right-Arm Fast/Med',
 'AR Adams': '⚡ Right-Arm Fast/Med',
 'J Srinath': '⚡ Right-Arm Fast/Med',
 'MJ Mason': '⚡ Right-Arm Fast/Med',
 'RM Haq': '🌀 Off Spin',
 'JH Davey': '⚡ Right-Arm Fast/Med',
 'PR Stirling': '🌀 Off Spin',
 'PM Seelaar': '🌀 Slow Left-Arm Orth',
 'Nadeem Ahmed': '🌀 Slow Left-Arm Orth',
 'Nasir Hossain': '🌀 Off Spin',
 'GB Brent': '⚡ Right-Arm Fast/Med',
 'RJ Sidebottom': '⚡ Left-Arm Fast/Med',
 'M Dillon': '⚡ Right-Arm Fast/Med',
 'SM Ervine': '⚡ Right-Arm Fast/Med',
 'H Osinde': '⚡ Right-Arm Fast/Med',
 'HS Baidwan': '⚡ Right-Arm Fast/Med',
 'Khaled Mahmud': '⚡ Right-Arm Fast/Med',
 'NN Odhiambo': '⚡ Right-Arm Fast/Med',
 'Sohag Gazi': '🌀 Off Spin',
 'DNT Zoysa': '⚡ Left-Arm Fast/Med',
 'Aizaz Cheema': '⚡ Right-Arm Fast/Med',
 'SW Masakadza': '⚡ Right-Arm Fast/Med',
 'SC Ganguly': '⚡ Right-Arm Fast/Med',
 'SR Patel': '🌀 Slow Left-Arm Orth',
 'S Dhaniram': '🌀 Slow Left-Arm Orth',
 'DS Lehmann': '🌀 Slow Left-Arm Orth',
 'WW Hinds': '⚡ Right-Arm Fast/Med',
 'RMS Eranga': '⚡ Right-Arm Fast/Med',
 'CO Obuya': '🌀 Leg Spin',
 'DT Christian': '⚡ Right-Arm Fast/Med',
 'PP Ojha': '🌀 Slow Left-Arm Orth',
 'Kabir Ali': '⚡ Right-Arm Fast/Med',
 'MH Yardy': '🌀 Slow Left-Arm Orth',
 'CL Cairns': '⚡ Right-Arm Fast/Med',
 'Anwar Ali': '⚡ Right-Arm Fast/Med',
 'N Boje': '🌀 Slow Left-Arm Orth',
 'RN ten Doeschate': '⚡ Right-Arm Fast/Med',
 'Rahat Ali': '⚡ Left-Arm Fast/Med',
 'Khurram Chohan': '⚡ Right-Arm Fast/Med',
 'DJ Hussey': '🌀 Off Spin',
 'GC Smith': '🌀 Off Spin',
 'JM Davison': '🌀 Off Spin',
 'JJ van der Wath': '⚡ Right-Arm Fast/Med',
 'Alok Kapali': '🌀 Leg Spin',
 'HA Varaiya': '🌀 Slow Left-Arm Orth',
 'Shabbir Ahmed': '⚡ Right-Arm Fast/Med',
 'KS Lokuarachchi': '🌀 Leg Spin',
 'AG Wharf': '⚡ Right-Arm Fast/Med',
 'I Wardlaw': '⚡ Right-Arm Fast/Med',
 'VC Drakes': '⚡ Right-Arm Fast/Med',
 'AR Caddick': '⚡ Right-Arm Fast/Med',
 'TBM de Leede': '⚡ Right-Arm Fast/Med',
 'LJ Wright': '⚡ Right-Arm Fast/Med',
 'JM Kemp': '⚡ Right-Arm Fast/Med',
 'EC Rainsford': '⚡ Right-Arm Fast/Med',
 'Suhrawadi Shuvo': '🌀 Slow Left-Arm Orth',
 'J Lewis': '⚡ Right-Arm Fast/Med',
 'KAD Hurdle': '⚡ Right-Arm Fast/Med',
 'UWMBCA Welegedara': '⚡ Left-Arm Fast/Med',
 'RR Sarwan': '🌀 Leg Spin'}

PLAYER_ROLES = {'JE Root': 'Batter',
 'HC Brook': 'Batter',
 'BM Duckett': 'Batter',
 'Z Crawley': 'Batter',
 'JC Buttler': 'Batter',
 'JM Bairstow': 'Batter',
 'PD Salt': 'Batter',
 'BA Stokes': 'Batting All-Rounder',
 'LS Livingstone': 'Batting All-Rounder',
 'JG Bethell': 'Batting All-Rounder',
 'MM Ali': 'Bowling All-Rounder',
 'SM Curran': 'Bowling All-Rounder',
 'LA Dawson': 'Bowling All-Rounder',
 'AU Rashid': 'Bowler',
 'MA Wood': 'Bowler',
 'J Archer': 'Bowler',
 'J Overton': 'Bowler',
 'Rehan Ahmed': 'Bowling All-Rounder',
 'AAP Atkinson': 'Bowler',
 'AD Hales': 'Batter',
 'BA Carse': 'Bowler',
 'BT Foakes': 'Batter',
 'C Overton': 'Bowling All-Rounder',
 'CJ Jordan': 'Bowler',
 'CR Woakes': 'Bowling All-Rounder',
 'DA Payne': 'Bowler',
 'DJ Malan': 'Batter',
 'DJ Willey': 'Bowling All-Rounder',
 'DR Mousley': 'Batting All-Rounder',
 'EJG Morgan': 'Batter',
 'GLS Scrimshaw': 'Bowler',
 'JA Simpson': 'Batter',
 'JA Turner': 'Bowler',
 'JC Archer': 'Bowler',
 'JJ Roy': 'Batter',
 'JL Denly': 'Batting All-Rounder',
 'JL Smith': 'Batter',
 'JM Cox': 'Batter',
 'JM Vince': 'Batter',
 'JT Ball': 'Bowler',
 'L Gregory': 'Bowling All-Rounder',
 'L Wood': 'Bowler',
 'LE Plunkett': 'Bowler',
 'MJ Potts': 'Bowler',
 'MW Parkinson': 'Bowler',
 'OP Stone': 'Bowler',
 'RJW Topley': 'Bowler',
 'S Baker': 'Bowler',
 'S Mahmood': 'Bowler',
 'SCJ Broad': 'Bowler',
 'SR Hain': 'Batter',
 'ST Finn': 'Bowler',
 'SW Billings': 'Batter',
 'T Banton': 'Batter',
 'TK Curran': 'Bowling All-Rounder',
 'TS Roland-Jones': 'Bowler',
 'TW Hartley': 'Bowler',
 'WG Jacks': 'Batting All-Rounder',
 'A Zampa': 'Bowler',
 'AC Agar': 'Bowling All-Rounder',
 'AJ Finch': 'Batter',
 'AJ Turner': 'Batting All-Rounder',
 'AJ Tye': 'Bowler',
 'AM Hardie': 'Bowling All-Rounder',
 'AT Carey': 'Batter',
 'B Stanlake': 'Bowler',
 'BJ Dwarshuis': 'Bowler',
 'BR McDermott': 'Batter',
 'C Connolly': 'Batting All-Rounder',
 'C Green': 'Bowling All-Rounder',
 'CA Lynn': 'Batter',
 'CL White': 'Batter',
 'CP Tremain': 'Bowler',
 'DA Warner': 'Batter',
 'DJ Worrall': 'Bowler',
 'DJM Short': 'Batter',
 'GJ Bailey': 'Batter',
 'GJ Maxwell': 'Batting All-Rounder',
 'HWR Cartwright': 'Batter',
 'J Fraser-McGurk': 'Batter',
 'JA Richardson': 'Bowler',
 'JM Mennie': 'Bowler',
 'JP Behrendorff': 'Bowler',
 'JP Faulkner': 'Bowling All-Rounder',
 'JP Inglis': 'Batter',
 'JR Hazlewood': 'Bowler',
 'JR Philippe': 'Batter',
 'JW Hastings': 'Bowling All-Rounder',
 'KW Richardson': 'Bowler',
 'LR Morris': 'Bowler',
 'M Labuschagne': 'Batter',
 'MA Starc': 'Bowler',
 'MC Henriques': 'Bowling All-Rounder',
 'MG Neser': 'Bowler',
 'MJ Owen': 'Batter',
 'MJ Swepson': 'Bowler',
 'MP Kuhnemann': 'Bowler',
 'MP Stoinis': 'Bowling All-Rounder',
 'MR Marsh': 'Batting All-Rounder',
 'MS Wade': 'Batter',
 'MT Renshaw': 'Batter',
 'MW Short': 'Batting All-Rounder',
 'NM Coulter-Nile': 'Bowler',
 'NM Lyon': 'Bowler',
 'NT Ellis': 'Bowler',
 'PJ Cummins': 'Bowler',
 'PM Siddle': 'Bowler',
 'PSP Handscomb': 'Batter',
 'RP Meredith': 'Bowler',
 'SA Abbott': 'Bowling All-Rounder',
 'SD Heazlett': 'Batter',
 'SE Marsh': 'Batter',
 'SH Johnson': 'Bowler',
 'SM Boland': 'Bowler',
 'SPD Smith': 'Batter',
 'T Sangha': 'Bowler',
 'TD Paine': 'Batter',
 'TH David': 'Batter',
 'TM Head': 'Batter',
 'UT Khawaja': 'Batter',
 'W Sutherland': 'Bowling All-Rounder',
 'WA Agar': 'Bowler',
 'XC Bartlett': 'Bowler',
 'K Rabada': 'Bowler',
 'A Nortje': 'Bowler',
 'G Coetzee': 'Bowler',
 'L Ngidi': 'Bowler',
 'OEG Baartman': 'Bowler',
 'AL Phehlukwayo': 'Bowling All-Rounder',
 'PWA Mulder': 'Bowling All-Rounder',
 'M Jansen': 'Bowling All-Rounder',
 'N Burger': 'Bowler',
 'KA Maharaj': 'Bowler',
 'BC Fortuin': 'Bowler',
 'T Shamsi': 'Bowler',
 'AB de Villiers': 'Batter',
 'AK Markram': 'Batting All-Rounder',
 'AM Phangiso': 'Bowler',
 'BE Hendricks': 'Bowler',
 'C Bosch': 'Bowling All-Rounder',
 'C Jonker': 'Batter',
 'CH Morris': 'Bowling All-Rounder',
 'CJ Dala': 'Bowler',
 'Codi Yusuf': 'Bowler',
 'D Brevis': 'Batter',
 'D Elgar': 'Batter',
 'D Ferreira': 'Batting All-Rounder',
 'D Olivier': 'Bowler',
 'D Paterson': 'Bowler',
 'D Pretorius': 'Bowling All-Rounder',
 'D Wiese': 'Bowling All-Rounder',
 'DA Miller': 'Batter',
 'DM Dupavillon': 'Bowler',
 'DW Steyn': 'Bowler',
 'E Bosch': 'Bowling All-Rounder',
 'F Behardien': 'Batting All-Rounder',
 'F du Plessis': 'Batter',
 'GF Linde': 'Bowling All-Rounder',
 'H Klaasen': 'Batter',
 'HE van der Dussen': 'Batter',
 'HM Amla': 'Batter',
 'Imran Tahir': 'Bowler',
 'JF Smith': 'Bowling All-Rounder',
 'JN Malan': 'Batter',
 'JP Duminy': 'Batting All-Rounder',
 'JT Smuts': 'Batting All-Rounder',
 'K Verreynne': 'Batter',
 'K Zondo': 'Batter',
 'KJ Abbott': 'Bowler',
 'KT Maphaka': 'Bowler',
 'L Sipamla': 'Bowler',
 'LB Williams': 'Bowler',
 'LG Pretorius': 'Batter',
 'M Morkel': 'Bowler',
 'M Mpongwana': 'Bowling All-Rounder',
 'MP Breetzke': 'Batter',
 'N Peter': 'Bowler',
 'P Subrayen': 'Bowler',
 'Q de Kock': 'Batter',
 'RA Herman': 'Batter',
 'RD Rickelton': 'Batter',
 'RR Hendricks': 'Batter',
 'RR Rossouw': 'Batter',
 'S Muthusamy': 'Bowling All-Rounder',
 'S Qeshile': 'Batter',
 'SSB Magala': 'Bowler',
 'T Bavuma': 'Batter',
 'T Stubbs': 'Batter',
 'T de Zorzi': 'Batter',
 'WD Parnell': 'Bowling All-Rounder',
 'Zubayr Hamza': 'Batter',
 'TG Southee': 'Bowler',
 'MJ Henry': 'Bowler',
 'LH Ferguson': 'Bowler',
 'AF Milne': 'Bowler',
 'KA Jamieson': 'Bowler',
 'BV Sears': 'Bowler',
 "W O'Rourke": 'Bowler',
 'TA Boult': 'Bowler',
 'MJ Santner': 'Bowling All-Rounder',
 'R Ravindra': 'Batting All-Rounder',
 'IS Sodhi': 'Bowler',
 'GD Phillips': 'Batter',
 'MG Bracewell': 'Batting All-Rounder',
 'DJ Mitchell': 'Batting All-Rounder',
 'JR Lennox': 'Bowler',
 'A Ashok': 'Bowler',
 'AP Devcich': 'Batting All-Rounder',
 'BG Lister': 'Bowler',
 'BJ Watling': 'Batter',
 'BM Tickner': 'Bowler',
 'C Munro': 'Batter',
 'C de Grandhomme': 'Bowling All-Rounder',
 'CE McConchie': 'Batting All-Rounder',
 'CJ Anderson': 'Bowling All-Rounder',
 'CJ Bowes': 'Batter',
 'D Cleaver': 'Batter',
 'D Foxcroft': 'Batter',
 'DAJ Bracewell': 'Bowling All-Rounder',
 'DG Brownlie': 'Batter',
 'DP Conway': 'Batter',
 'FH Allen': 'Batter',
 'GH Worker': 'Batter',
 'HB Shipley': 'Bowler',
 'HK Bennett': 'Bowler',
 'HM Nicholls': 'Batter',
 'JA Clarkson': 'Bowling All-Rounder',
 'JA Duffy': 'Bowler',
 'JDS Neesham': 'Bowling All-Rounder',
 'JS Patel': 'Bowler',
 'KDC Clarke': 'Batter',
 'KS Williamson': 'Batter',
 'L Ronchi': 'Batter',
 'LRPL Taylor': 'Batter',
 'MA Abbas': 'Bowler',
 'MJ Guptill': 'Batter',
 'MJ Hay': 'Batter',
 'MS Chapman': 'Batter',
 'NF Kelly': 'Batter',
 'NG Smith': 'Bowling All-Rounder',
 'NT Broom': 'Batter',
 'RA Mariu': 'Batter',
 'SC Kuggeleijn': 'Bowling All-Rounder',
 'SHA Rance': 'Bowler',
 'TA Blundell': 'Batter',
 'TB Robinson': 'Batter',
 'TD Astle': 'Bowler',
 'TL Seifert': 'Batter',
 'TWM Latham': 'Batter',
 'WA Young': 'Batter',
 'ZGF Foulkes': 'Bowler',
 'MS Dhoni': 'Batter',
 'V Kohli': 'Batter',
 'RG Sharma': 'Batter',
 'S Dhawan': 'Batter',
 'KL Rahul': 'Batter',
 'RR Pant': 'Batter',
 'SS Iyer': 'Batter',
 'SA Yadav': 'Batter',
 'Shubman Gill': 'Batter',
 'Ishan Kishan': 'Batter',
 'SV Samson': 'Batter',
 'AM Rahane': 'Batter',
 'AT Rayudu': 'Batter',
 'MK Pandey': 'Batter',
 'KD Karthik': 'Batter',
 'SK Raina': 'Batting All-Rounder',
 'Yuvraj Singh': 'Batting All-Rounder',
 'KM Jadhav': 'Batting All-Rounder',
 'HH Pandya': 'Bowling All-Rounder',
 'RA Jadeja': 'Bowling All-Rounder',
 'R Ashwin': 'Bowling All-Rounder',
 'AR Patel': 'Bowling All-Rounder',
 'SN Thakur': 'Bowling All-Rounder',
 'DL Chahar': 'Bowling All-Rounder',
 'KH Pandya': 'Bowling All-Rounder',
 'Washington Sundar': 'Bowling All-Rounder',
 'Shahbaz Ahmed': 'Bowling All-Rounder',
 'DJ Hooda': 'Batting All-Rounder',
 'V Shankar': 'Batting All-Rounder',
 'VR Iyer': 'Batting All-Rounder',
 'S Dube': 'Batting All-Rounder',
 'N Rana': 'Batting All-Rounder',
 'R Parag': 'Batting All-Rounder',
 'Tilak Varma': 'Batting All-Rounder',
 'Nithish Kumar Reddy': 'Bowling All-Rounder',
 'JJ Bumrah': 'Bowler',
 'Mohammed Shami': 'Bowler',
 'Mohammed Siraj': 'Bowler',
 'B Kumar': 'Bowler',
 'YS Chahal': 'Bowler',
 'Kuldeep Yadav': 'Bowler',
 'Ravi Bishnoi': 'Bowler',
 'A Mishra': 'Bowler',
 'RD Chahar': 'Bowler',
 'UT Yadav': 'Bowler',
 'Umran Malik': 'Bowler',
 'Navdeep Saini': 'Bowler',
 'T Natarajan': 'Bowler',
 'KK Ahmed': 'Bowler',
 'JD Unadkat': 'Bowler',
 'M Prasidh Krishna': 'Bowler',
 'Arshdeep Singh': 'Bowler',
 'Harshit Rana': 'Bowler',
 'Mukesh Kumar': 'Bowler',
 'Avesh Khan': 'Bowler',
 'KR Sen': 'Bowler',
 'RD Gaikwad': 'Batter',
 'YBK Jaiswal': 'Batter',
 'RK Singh': 'Batter',
 'RM Patidar': 'Batter',
 'B Sai Sudharsan': 'Batter',
 'PP Shaw': 'Batter',
 'MA Agarwal': 'Batter',
 'FY Fazal': 'Batter',
 'KK Nair': 'Batter',
 'K Gowtham': 'Bowler',
 'J Yadav': 'Bowler',
 'DS Kulkarni': 'Bowler',
 'S Kaul': 'Bowler',
 'C Sakariya': 'Bowler',
 'BB Sran': 'Bowler',
 'CV Varun': 'Bowler',
 'Aamer Jamal': 'Bowling All-Rounder',
 'Aamer Yamin': 'Bowling All-Rounder',
 'Abdullah Shafique': 'Batter',
 'Abid Ali': 'Batter',
 'Abrar Ahmed': 'Bowler',
 'Agha Salman': 'Batting All-Rounder',
 'Ahmed Shehzad': 'Batter',
 'Akif Javed': 'Bowler',
 'Asad Shafiq': 'Batter',
 'Asif Ali': 'Batter',
 'Azhar Ali': 'Batter',
 'Babar Azam': 'Batter',
 'Danish Aziz': 'Batting All-Rounder',
 'Faheem Ashraf': 'Bowling All-Rounder',
 'Faisal Akram': 'Bowler',
 'Fakhar Zaman': 'Batter',
 'Haider Ali': 'Batter',
 'Haris Rauf': 'Bowler',
 'Haris Sohail': 'Batter',
 'Hasan Ali': 'Bowler',
 'Haseebullah Khan': 'Batter',
 'Hassan Nawaz': 'Batter',
 'Hussain Talat': 'Batting All-Rounder',
 'Iftikhar Ahmed': 'Batting All-Rounder',
 'Ihsanullah': 'Bowler',
 'Imad Wasim': 'Bowling All-Rounder',
 'Imam-ul-Haq': 'Batter',
 'Irfan Khan': 'Batter',
 'Junaid Khan': 'Bowler',
 'Kamran Akmal': 'Batter',
 'Kamran Ghulam': 'Batting All-Rounder',
 'Khushdil Shah': 'Batting All-Rounder',
 'Mohammad Abbas': 'Bowler',
 'Mohammad Ali': 'Bowler',
 'Mohammad Amir': 'Bowler',
 'Mohammad Hafeez': 'Batting All-Rounder',
 'Mohammad Haris': 'Batter',
 'Mohammad Hasnain': 'Bowler',
 'Mohammad Irfan': 'Bowler',
 'Mohammad Nawaz': 'Bowling All-Rounder',
 'Mohammad Nawaz (3)': 'Bowling All-Rounder',
 'Mohammad Rizwan': 'Batter',
 'Mohammad Wasim': 'Bowling All-Rounder',
 'Muhammad Musa': 'Bowler',
 'Naseem Shah': 'Bowler',
 'Rumman Raees': 'Bowler',
 'Saad Ali': 'Batter',
 'Saim Ayub': 'Batter',
 'Sami Aslam': 'Batter',
 'Sarfraz Ahmed': 'Batter',
 'Saud Shakeel': 'Batter',
 'Shadab Khan': 'Bowling All-Rounder',
 'Shaheen Shah Afridi': 'Bowler',
 'Shahnawaz Dhani': 'Bowler',
 'Shan Masood': 'Batter',
 'Sharjeel Khan': 'Batter',
 'Shoaib Malik': 'Batting All-Rounder',
 'Sohaib Maqsood': 'Batter',
 'Sohail Khan': 'Bowler',
 'Sufiyan Muqeem': 'Bowler',
 'Tayyab Tahir': 'Batter',
 'Umar Akmal': 'Batter',
 'Umar Amin': 'Batter',
 'Umar Gul': 'Bowler',
 'Usama Mir': 'Bowler',
 'Usman Khan': 'Batter',
 'Usman Khan (2)': 'Batter',
 'Usman Qadir': 'Bowler',
 'Usman Shinwari': 'Bowler',
 'Wahab Riaz': 'Bowler',
 'Yasir Shah': 'Bowler',
 'Zahid Mahmood': 'Bowler',
 'Zaman Khan': 'Bowler',
 'A Dananjaya': 'Bowler',
 'AD Mathews': 'Batting All-Rounder',
 'AK Perera': 'Batting All-Rounder',
 'B Fernando': 'Bowler',
 'BMAJ Mendis': 'Bowling All-Rounder',
 'BOP Fernando': 'Batter',
 'C Gunasekara': 'Batter',
 'C Karunaratne': 'Bowling All-Rounder',
 'C Wickramasinghe': 'Bowling All-Rounder',
 'CAK Rajitha': 'Bowler',
 'CBRLS Kumara': 'Bowler',
 'CK Kapugedera': 'Batter',
 'D Lakshan': 'Bowling All-Rounder',
 'D Madushanka': 'Bowler',
 'DAS Gunaratne': 'Batting All-Rounder',
 'DS Weerakkody': 'Batter',
 'DSK Madushanka': 'Bowler',
 'E Malinga': 'Bowler',
 'EMDY Munaweera': 'Batter',
 'FDM Karunaratne': 'Batter',
 'GSNFG Jayasuriya': 'Batter',
 'HDRL Thirimanne': 'Batter',
 'I Udana': 'Bowling All-Rounder',
 'KMC Bandara': 'Bowler',
 'KMDN Kulasekara': 'Bowler',
 'KNA Bandara': 'Bowler',
 'KNM Fernando': 'Batter',
 'LD Chandimal': 'Batter',
 'LD Madushanka': 'Bowling All-Rounder',
 'M Bhanuka': 'Batter',
 'M Shiraz': 'Bowler',
 'M Theekshana': 'Bowler',
 'MA Aponso': 'Bowler',
 'MADI Hemantha': 'Bowler',
 'MD Gunathilaka': 'Batter',
 'MD Shanaka': 'Bowling All-Rounder',
 'MDK Perera': 'Bowling All-Rounder',
 'MDKJ Perera': 'Batter',
 'MF Maharoof': 'Bowling All-Rounder',
 'MNK Fernando': 'Bowling All-Rounder',
 'MVT Fernando': 'Bowler',
 'N Dickwella': 'Batter',
 'N Pradeep': 'Bowler',
 'NGRP Jayasuriya': 'Bowler',
 'NLTC Perera': 'Bowling All-Rounder',
 'P Jayawickrama': 'Bowler',
 'PADLR Sandakan': 'Bowler',
 'PARP Perera': 'Batter',
 'PBB Rajapaksa': 'Batter',
 'PC de Silva': 'Bowling All-Rounder',
 'PHKD Mendis': 'Batter',
 'PLS Gamage': 'Bowler',
 'PM Pushpakumara': 'Bowler',
 'PVD Chameera': 'Bowler',
 'RAS Lakmal': 'Bowler',
 'RMMP Rathnayake': 'Bowler',
 'RMS Eranga': 'Bowler',
 'RTM Mendis': 'Bowling All-Rounder',
 'S Daniel': 'Batter',
 'S Prasanna': 'Bowling All-Rounder',
 'S Randiv': 'Bowler',
 'S Samarawickrama': 'Batter',
 'SL Malinga': 'Bowler',
 'SS Pathirana': 'Bowling All-Rounder',
 'SSD Arachchige': 'Batting All-Rounder',
 'TAM Siriwardana': 'Batting All-Rounder',
 'TM Dilshan': 'Batter',
 'WIA Fernando': 'Batter',
 'WU Tharanga': 'Batter',
 'P Nissanka': 'Batter',
 'BKG Mendis': 'Batter',
 'K Mishara': 'Batter',
 'A Athanaze': 'Batter',
 'A Phillip': 'Bowler',
 'AD Russell': 'Bowling All-Rounder',
 'ADS Fletcher': 'Batter',
 'AM McCarthy': 'Batter',
 'AR Nurse': 'Bowling All-Rounder',
 'Akeem Jordan': 'Bowler',
 'C Hemraj': 'Batter',
 'CH Gayle': 'Batter',
 'CK Holder': 'Bowler',
 'CR Brathwaite': 'Bowling All-Rounder',
 'D Bishoo': 'Bowler',
 'DC Drakes': 'Bowler',
 'FA Allen': 'Bowling All-Rounder',
 'HR Walsh': 'Bowler',
 'J Blades': 'Batter',
 'JD Campbell': 'Batter',
 'JE Taylor': 'Bowler',
 'JL Carter': 'Batter',
 'JN Mohammed': 'Batter',
 'JO Holder': 'Bowling All-Rounder',
 'K Sinclair': 'Bowler',
 'KA Pollard': 'Batting All-Rounder',
 'KAJ Roach': 'Bowler',
 'KAR Hodge': 'Batting All-Rounder',
 'KC Brathwaite': 'Batter',
 'KJ Harding': 'Bowler',
 'KMA Paul': 'Bowling All-Rounder',
 'KOK Williams': 'Bowler',
 'KR Mayers': 'Batting All-Rounder',
 'KU Carty': 'Batter',
 'MJ Mindley': 'Bowler',
 'ML Cummins': 'Bowler',
 'MN Samuels': 'Batter',
 'MW Forde': 'Bowler',
 'N Pooran': 'Batter',
 'NE Bonner': 'Batter',
 'NO Miller': 'Bowler',
 'OC McCoy': 'Bowler',
 'OF Smith': 'Bowler',
 'R Powell': 'Batter',
 'RA Reifer': 'Bowling All-Rounder',
 'RR Beaton': 'Bowler',
 'S Joseph': 'Bowler',
 'SE Rutherford': 'Batter',
 'SH Lewis': 'Bowler',
 'SJ Benn': 'Bowler',
 'SK Springer': 'Bowling All-Rounder',
 'SP Narine': 'Bowler',
 'SS Cottrell': 'Bowler',
 'ST Gabriel': 'Bowler',
 'V Permaul': 'Bowler',
 'Y Cariah': 'Bowler',
 'Taskin Ahmed': 'Bowler',
 'Hasan Mahmud': 'Bowler',
 'Ebadot Hossain': 'Bowler',
 'Tanzim Hasan Sakib': 'Bowler',
 'Mustafizur Rahman': 'Bowler',
 'Shoriful Islam': 'Bowler',
 'Shakib Al Hasan': 'Bowling All-Rounder',
 'Nasum Ahmed': 'Bowler',
 'Taijul Islam': 'Bowler',
 'Mehedi Hasan Miraz': 'Bowling All-Rounder',
 'Rishad Hossain': 'Bowler',
 'Afif Hossain': 'Batting All-Rounder',
 'Anamul Haque': 'Batter',
 'Litton Das': 'Batter',
 'Mahmudullah': 'Batting All-Rounder',
 'Mahedi Hasan': 'Bowling All-Rounder',
 'Mashrafe Mortaza': 'Bowler',
 'Mehidy Hasan Miraz': 'Bowling All-Rounder',
 'Mohammad Saifuddin': 'Bowling All-Rounder',
 'Mosaddek Hossain': 'Batting All-Rounder',
 'Mushfiqur Rahim': 'Batter',
 'Nayeem Hasan': 'Bowler',
 'Rubel Hossain': 'Bowler',
 'Soumya Sarkar': 'Batting All-Rounder',
 'Sunzamul Islam': 'Bowler',
 'Azmatullah Omarzai': 'Bowling All-Rounder',
 'Fareed Ahmad': 'Bowler',
 'Fazalhaq Farooqi': 'Bowler',
 'Gulbadin Naib': 'Bowling All-Rounder',
 'Mohammad Nabi': 'Bowling All-Rounder',
 'Mujeeb Ur Rahman': 'Bowler',
 'Naveen-ul-Haq': 'Bowler',
 'Noor Ahmad': 'Bowler',
 'Qais Ahmad': 'Bowler',
 'Rashid Khan': 'Bowling All-Rounder',
 'AM Ghazanfar': 'Bowler',
 'Hamid Hassan': 'Bowler',
 'Izatullah Dawlatzai': 'Bowler',
 'Karim Janat': 'Bowling All-Rounder',
 'Mirwais Ashraf': 'Bowling All-Rounder',
 'Mohammad Shahzad': 'Batter',
 'Najibullah Zadran': 'Batter',
 'Nangeyalia Kharote': 'Bowling All-Rounder',
 'Samiullah Shinwari': 'Batting All-Rounder',
 'Sharafuddin Ashraf': 'Bowling All-Rounder',
 'Yamin Ahmadzai': 'Bowler',
 'A Ndlovu': 'Bowler',
 'B Evans': 'Bowling All-Rounder',
 'B Madande': 'Batter',
 'B Muzarabani': 'Bowler',
 'BB Chari': 'Batter',
 'CJ Chibhabha': 'Batting All-Rounder',
 'CR Ervine': 'Batter',
 'CT Mumba': 'Bowler',
 'DT Tiripano': 'Bowling All-Rounder',
 'F Akram': 'Bowler',
 'H Masakadza': 'Batter',
 'Innocent Kaia': 'Batter',
 'J Gumbie': 'Batter',
 'KM Jarvis': 'Bowler',
 'LM Jongwe': 'Bowling All-Rounder',
 'M Shumba': 'Batting All-Rounder',
 'N Madziva': 'Bowling All-Rounder',
 'R Burl': 'Batting All-Rounder',
 'R Chakabva': 'Batter',
 'R Ngarava': 'Bowler',
 'SC Williams': 'Batting All-Rounder',
 'Sikandar Raza': 'Bowling All-Rounder',
 'T Maruma': 'Batter',
 'TL Chatara': 'Bowler',
 'TS Chisoro': 'Bowler',
 'V Sibanda': 'Batter',
 'WP Masakadza': 'Bowler',
 'AR McBrine': 'Bowling All-Rounder',
 'B McCarthy': 'Bowler',
 'C Campher': 'Bowling All-Rounder',
 'CA Young': 'Bowler',
 'F Hand': 'Bowling All-Rounder',
 'G Hume': 'Bowler',
 'GH Dockrell': 'Batting All-Rounder',
 'GJ Delany': 'Batting All-Rounder',
 'Harry Tector': 'Batter',
 'Joshua Little': 'Bowler',
 'L Tucker': 'Batter',
 'MR Adair': 'Bowling All-Rounder',
 'PR Stirling': 'Batter',
 'SC Getkate': 'Bowling All-Rounder',
 'Simi Singh': 'Bowling All-Rounder',
 'WB Rankin': 'Bowler',
 'Aryan Dutt': 'Bowler',
 'Bas de Leede': 'Bowling All-Rounder',
 'Brandon Glover': 'Bowler',
 'Fred Klaassen': 'Bowler',
 'Logan van Beek': 'Bowling All-Rounder',
 "Max O'Dowd": 'Batter',
 'Paul van Meekeren': 'Bowler',
 'Roelof van der Merwe': 'Bowling All-Rounder',
 'Ryan Klein': 'Bowler',
 'SA Engelbrecht': 'Batter',
 'Scott Edwards': 'Batter',
 'Shariz Ahmad': 'Bowler',
 'Sikander Zulfiqar': 'Bowling All-Rounder',
 'Tim Pringle': 'Bowler',
 'Vivian Kingma': 'Bowler',
 'Vikramjit Singh': 'Batter',
 'PWH de Silva':'Bowling All-Rounder'
 
 }
