"""
config/teams.py
Contains static reference data for Teams (Colors) and Players (Bowling Styles).

--- 🛠️ ARCHITECTURAL MAINTENANCE GUIDE (v2.5) ---
1. PURPOSE: 
   This file provides mapping for the 'Threat Matrix' (Batter vs Style). 
   It includes all international players from the last 10 years + top 200 historical 
   legends to support career-long stats for veterans (Kohli, Rohit, Starc, etc.).

2. CLEANING CYCLE (PRUNING):
   - Frequency: Every 2-3 years, or after a major generation of players retire.
   - Logic: Run 'scripts/check_bowler_coverage.py'. If a bowler in this dictionary 
     has not bowled a ball to ANY active batter in the last 5 years of the dataset, 
     they are 'safe to prune' to maintain engine efficiency.

3. SCALING:
   - For new debutants: Run 'scripts/find_missing_players.py' to identify new gaps.
   - Long Term: Once the 2008-2012 debut generation retire, the 'Historical Legends' 
     section can be moved to an external JSON or archived to reduce file size.
-------------------------------------------------
"""

# Team Hex Colors for UI (Jersey Colors)
TEAM_COLORS = {
    'India': '#1F34D1', 'Australia': '#D4AF37', 'England': '#C51130',
    'South Africa': '#006A4E', 'New Zealand': '#222222', 'Pakistan': '#01411C',
    'West Indies': '#7B0028', 'Sri Lanka': '#0E3292', 'Bangladesh': '#006A4E',
    'Afghanistan': '#0063B2', 'Zimbabwe': '#D40000', 'Ireland': '#009D4E',
    'Netherlands': '#FF6600', 'Visitors': '#808080'
}

# ICC ODI Rankings (v3.3 Refinement)
ODI_RANKINGS = {
    "India": 1,
    "New Zealand": 2,
    "Australia": 3,
    "Pakistan": 4,
    "South Africa": 5,
    "Sri Lanka": 6,
    "Afghanistan": 7,
    "England": 8,
    "West Indies": 9,
    "Bangladesh": 10
}

# Bowling Style Categories (For Reference & Consistency)
STYLE_RIGHT_PACE = '⚡ Right-Arm Fast/Med'
STYLE_LEFT_PACE = '⚡ Left-Arm Fast/Med'
STYLE_OFF_SPIN = '🌀 Off Spin'
STYLE_SLA = '🌀 Slow Left-Arm Orth'
STYLE_LEG_SPIN = '🌀 Leg Spin'
STYLE_LEFT_UNORTHODOX = '🌀 Left-Arm Unorthodox'

# Bowler Styles Dictionary (For Matchup Analysis)
BOWLER_STYLES = {
    # --- AUSTRALIA ---
    'MA Starc': STYLE_LEFT_PACE,
    'JR Hazlewood': STYLE_RIGHT_PACE,
    'PJ Cummins': STYLE_RIGHT_PACE,
    'JA Richardson': STYLE_RIGHT_PACE,
    'Sean Abbott': STYLE_RIGHT_PACE,
    'SA Abbott': STYLE_RIGHT_PACE,
    'NT Ellis': STYLE_RIGHT_PACE,
    'XC Bartlett': STYLE_RIGHT_PACE,
    'C Green': STYLE_RIGHT_PACE,
    'MR Marsh': STYLE_RIGHT_PACE,
    'MP Stoinis': STYLE_RIGHT_PACE,
    'A Zampa': STYLE_LEG_SPIN,
    'NM Lyon': STYLE_OFF_SPIN,
    'GJ Maxwell': STYLE_OFF_SPIN,
    'AC Agar': STYLE_SLA,
    'AJ Finch': STYLE_SLA,
    'AJ Turner': STYLE_OFF_SPIN,
    'AJ Tye': STYLE_RIGHT_PACE,
    'AM Hardie': STYLE_RIGHT_PACE,
    'B Stanlake': STYLE_RIGHT_PACE,
    'BJ Dwarshuis': STYLE_LEFT_PACE,
    'C Connolly': STYLE_SLA,
    'CP Tremain': STYLE_RIGHT_PACE,
    'DJ Worrall': STYLE_RIGHT_PACE,
    'DJM Short': STYLE_LEFT_UNORTHODOX,
    'JM Mennie': STYLE_RIGHT_PACE,
    'JP Behrendorff': STYLE_LEFT_PACE,
    'JP Faulkner': STYLE_LEFT_PACE,
    'JW Hastings': STYLE_RIGHT_PACE,
    'KW Richardson': STYLE_RIGHT_PACE,
    'LR Morris': STYLE_RIGHT_PACE,
    'M Labuschagne': STYLE_LEG_SPIN,
    'MC Henriques': STYLE_RIGHT_PACE,
    'MG Neser': STYLE_RIGHT_PACE,
    'MJ Swepson': STYLE_LEG_SPIN,
    'MP Kuhnemann': STYLE_SLA,
    'MW Short': STYLE_OFF_SPIN,
    'NM Coulter-Nile': STYLE_RIGHT_PACE,
    'PM Siddle': STYLE_RIGHT_PACE,
    'RP Meredith': STYLE_RIGHT_PACE,
    'SH Johnson': STYLE_LEFT_PACE,
    'SM Boland': STYLE_RIGHT_PACE,
    'SPD Smith': STYLE_LEG_SPIN,
    'T Sangha': STYLE_LEG_SPIN,
    'TH David': STYLE_OFF_SPIN,
    'TM Head': STYLE_OFF_SPIN,
    'W Sutherland': STYLE_RIGHT_PACE,
    'WA Agar': STYLE_LEFT_PACE,

    # --- INDIA ---
    'JJ Bumrah': STYLE_RIGHT_PACE,
    'Mohammed Shami': STYLE_RIGHT_PACE,
    'Mohammed Siraj': STYLE_RIGHT_PACE,
    'Harshit Rana': STYLE_RIGHT_PACE,
    'M Prasidh Krishna': STYLE_RIGHT_PACE,
    'HH Pandya': STYLE_RIGHT_PACE,
    'Shardul Thakur': STYLE_RIGHT_PACE,
    'Nithish Kumar Reddy': STYLE_RIGHT_PACE,
    'Arshdeep Singh': STYLE_LEFT_PACE,
    'R Ashwin': STYLE_OFF_SPIN,
    'Washington Sundar': STYLE_OFF_SPIN,
    'RA Jadeja': STYLE_SLA,
    'AR Patel': STYLE_SLA,
    'Kuldeep Yadav': STYLE_LEFT_UNORTHODOX, 
    'Ravi Bishnoi': STYLE_LEG_SPIN,
    'YS Chahal': STYLE_LEG_SPIN,
    'A Mishra': STYLE_LEG_SPIN,
    'RD Chahar': STYLE_LEG_SPIN,
    'B Kumar': STYLE_RIGHT_PACE,
    'UT Yadav': STYLE_RIGHT_PACE,
    'Umran Malik': STYLE_RIGHT_PACE,
    'Navdeep Saini': STYLE_RIGHT_PACE,
    'T Natarajan': STYLE_LEFT_PACE,
    'KK Ahmed': STYLE_LEFT_PACE,
    'JD Unadkat': STYLE_LEFT_PACE,
    'C Sakariya': STYLE_LEFT_PACE,
    'BB Sran': STYLE_LEFT_PACE,
    'DL Chahar': STYLE_RIGHT_PACE,
    'SN Thakur': STYLE_RIGHT_PACE,
    'S Kaul': STYLE_RIGHT_PACE,
    'Avesh Khan': STYLE_RIGHT_PACE,
    'Mukesh Kumar': STYLE_RIGHT_PACE,
    'KR Sen': STYLE_RIGHT_PACE,
    'DS Kulkarni': STYLE_RIGHT_PACE,
    'V Shankar': STYLE_RIGHT_PACE,
    'VR Iyer': STYLE_RIGHT_PACE,
    'S Dube': STYLE_RIGHT_PACE,
    'J Yadav': STYLE_OFF_SPIN,
    'K Gowtham': STYLE_OFF_SPIN,
    'Shahbaz Ahmed': STYLE_SLA,
    'KH Pandya': STYLE_SLA,
    'Yuvraj Singh': STYLE_SLA,
    'KM Jadhav': STYLE_OFF_SPIN,
    'SK Raina': STYLE_OFF_SPIN,
    'DJ Hooda': STYLE_OFF_SPIN,
    'RG Sharma': STYLE_OFF_SPIN,
    'V Kohli': STYLE_RIGHT_PACE,
    'AT Rayudu': STYLE_OFF_SPIN,
    'N Rana': STYLE_OFF_SPIN,
    'R Parag': STYLE_LEG_SPIN,
    'Tilak Varma': STYLE_OFF_SPIN,
    'SA Yadav': STYLE_OFF_SPIN,
    'SS Iyer': STYLE_LEG_SPIN,
    'MA Agarwal': STYLE_OFF_SPIN,
    'Shubman Gill': STYLE_OFF_SPIN,
    'B Sai Sudharsan': STYLE_LEG_SPIN,
    'RK Singh': STYLE_OFF_SPIN,
    'CV Varun': STYLE_LEG_SPIN,

    # --- ENGLAND ---
    'J Archer': STYLE_RIGHT_PACE,
    'MA Wood': STYLE_RIGHT_PACE,
    'O Stone': STYLE_RIGHT_PACE,
    'BA Carse': STYLE_RIGHT_PACE,
    'G Atkinson': STYLE_RIGHT_PACE,
    'AAP Atkinson': STYLE_RIGHT_PACE,
    'CR Woakes': STYLE_RIGHT_PACE,
    'S Mahmood': STYLE_RIGHT_PACE,
    'SM Curran': STYLE_LEFT_PACE,
    'RJW Topley': STYLE_LEFT_PACE,
    'L Wood': STYLE_LEFT_PACE,
    'AU Rashid': STYLE_LEG_SPIN,
    'Rehan Ahmed': STYLE_LEG_SPIN,
    'MM Ali': STYLE_OFF_SPIN,
    'LS Livingstone': STYLE_OFF_SPIN,
    'W Jacks': STYLE_OFF_SPIN,
    'WG Jacks': STYLE_OFF_SPIN,
    'LA Dawson': STYLE_SLA,
    'J Overton': STYLE_RIGHT_PACE,
    'JG Bethell': STYLE_SLA,
    'JE Root': STYLE_OFF_SPIN,
    'BA Stokes': STYLE_RIGHT_PACE,
    'C Overton': STYLE_RIGHT_PACE,
    'CJ Jordan': STYLE_RIGHT_PACE,
    'DA Payne': STYLE_LEFT_PACE,
    'DJ Malan': STYLE_LEG_SPIN,
    'DJ Willey': STYLE_LEFT_PACE,
    'DR Mousley': STYLE_OFF_SPIN,
    'GLS Scrimshaw': STYLE_RIGHT_PACE,
    'JA Turner': STYLE_RIGHT_PACE,
    'JC Archer': STYLE_RIGHT_PACE,
    'JL Denly': STYLE_LEG_SPIN,
    'JM Vince': STYLE_RIGHT_PACE,
    'JT Ball': STYLE_RIGHT_PACE,
    'L Gregory': STYLE_RIGHT_PACE,
    'LE Plunkett': STYLE_RIGHT_PACE,
    'MJ Potts': STYLE_RIGHT_PACE,
    'MW Parkinson': STYLE_LEG_SPIN,
    'OP Stone': STYLE_RIGHT_PACE,
    'S Baker': STYLE_LEFT_PACE,
    'SCJ Broad': STYLE_RIGHT_PACE,
    'ST Finn': STYLE_RIGHT_PACE,
    'TK Curran': STYLE_RIGHT_PACE,
    'TS Roland-Jones': STYLE_RIGHT_PACE,
    'TW Hartley': STYLE_SLA,
    

    # --- SOUTH AFRICA ---
    'K Rabada': STYLE_RIGHT_PACE,
    'A Nortje': STYLE_RIGHT_PACE,
    'G Coetzee': STYLE_RIGHT_PACE,
    'L Ngidi': STYLE_RIGHT_PACE,
    'O Baartman': STYLE_RIGHT_PACE,
    'OEG Baartman': STYLE_RIGHT_PACE,
    'AL Phehlukwayo': STYLE_RIGHT_PACE,
    'W Mulder': STYLE_RIGHT_PACE,
    'PWA Mulder': STYLE_RIGHT_PACE,
    'M Jansen': STYLE_LEFT_PACE,
    'N Burger': STYLE_LEFT_PACE,
    'KA Maharaj': STYLE_SLA,
    'BC Fortuin': STYLE_SLA,
    'T Shamsi': STYLE_LEFT_UNORTHODOX,
    'AK Markram': STYLE_OFF_SPIN,
    'AM Phangiso': STYLE_SLA,
    'BE Hendricks': STYLE_LEFT_PACE,
    'C Bosch': STYLE_RIGHT_PACE,
    'CH Morris': STYLE_RIGHT_PACE,
    'CJ Dala': STYLE_RIGHT_PACE,
    'Codi Yusuf': STYLE_RIGHT_PACE,
    'D Brevis': STYLE_LEG_SPIN,
    'D Ferreira': STYLE_OFF_SPIN,
    'D Olivier': STYLE_RIGHT_PACE,
    'D Paterson': STYLE_RIGHT_PACE,
    'D Pretorius': STYLE_RIGHT_PACE,
    'D Wiese': STYLE_RIGHT_PACE,
    'DM Dupavillon': STYLE_RIGHT_PACE,
    'DW Steyn': STYLE_RIGHT_PACE,
    'E Bosch': STYLE_RIGHT_PACE,
    'F Behardien': STYLE_RIGHT_PACE,
    'GF Linde': STYLE_SLA,
    'Imran Tahir': STYLE_LEG_SPIN,
    'JF Smith': STYLE_RIGHT_PACE,
    'JP Duminy': STYLE_OFF_SPIN,
    'JT Smuts': STYLE_SLA,
    'KJ Abbott': STYLE_RIGHT_PACE,
    'KT Maphaka': STYLE_LEFT_PACE,
    'L Sipamla': STYLE_RIGHT_PACE,
    'LB Williams': STYLE_RIGHT_PACE,
    'M Morkel': STYLE_RIGHT_PACE,
    'M Mpongwana': STYLE_RIGHT_PACE,
    'N Peter': STYLE_LEG_SPIN,
    'P Subrayen': STYLE_OFF_SPIN,
    'S Muthusamy': STYLE_SLA,
    'SSB Magala': STYLE_RIGHT_PACE,
    'T Stubbs': STYLE_OFF_SPIN,
    'WD Parnell': STYLE_LEFT_PACE,

    # --- NEW ZEALAND ---
    'TG Southee': STYLE_RIGHT_PACE,
    'MJ Henry': STYLE_RIGHT_PACE,
    'LH Ferguson': STYLE_RIGHT_PACE,
    'AF Milne': STYLE_RIGHT_PACE,
    'KA Jamieson': STYLE_RIGHT_PACE,
    'BN Sears': STYLE_RIGHT_PACE,
    'BV Sears': STYLE_RIGHT_PACE,
    'W O\'Rourke': STYLE_RIGHT_PACE,
    'TA Boult': STYLE_LEFT_PACE,
    'MJ Santner': STYLE_SLA,
    'R Ravindra': STYLE_SLA,
    'IS Sodhi': STYLE_LEG_SPIN,
    'GD Phillips': STYLE_OFF_SPIN,
    'MG Bracewell': STYLE_OFF_SPIN,
    'DJ Mitchell': STYLE_RIGHT_PACE,
    'JR Lennox': STYLE_SLA,
    'KDC Clarke': STYLE_RIGHT_PACE,
    'ZGF Foulkes': STYLE_RIGHT_PACE,
    'A Ashok': STYLE_LEG_SPIN,
    'AP Devcich': STYLE_SLA,
    'BG Lister': STYLE_LEFT_PACE,
    'BM Tickner': STYLE_RIGHT_PACE,
    'C Munro': STYLE_RIGHT_PACE,
    'C de Grandhomme': STYLE_RIGHT_PACE,
    'CE McConchie': STYLE_OFF_SPIN,
    'CJ Anderson': STYLE_LEFT_PACE,
    'DAJ Bracewell': STYLE_RIGHT_PACE,
    'HB Shipley': STYLE_RIGHT_PACE,
    'HK Bennett': STYLE_RIGHT_PACE,
    'JA Clarkson': STYLE_RIGHT_PACE,
    'JA Duffy': STYLE_RIGHT_PACE,
    'JDS Neesham': STYLE_RIGHT_PACE,
    'JS Patel': STYLE_OFF_SPIN,
    'KS Williamson': STYLE_OFF_SPIN,
    'MA Abbas': STYLE_RIGHT_PACE,
    'NG Smith': STYLE_RIGHT_PACE,
    'SC Kuggeleijn': STYLE_RIGHT_PACE,
    'SHA Rance': STYLE_RIGHT_PACE,
    'TD Astle': STYLE_LEG_SPIN,
    
    

    # --- PAKISTAN ---
    'Naseem Shah': STYLE_RIGHT_PACE,
    'Haris Rauf': STYLE_RIGHT_PACE,
    'Hasan Ali': STYLE_RIGHT_PACE,
    'Mohammad Wasim': STYLE_RIGHT_PACE,
    'Zaman Khan': STYLE_RIGHT_PACE,
    'Aamer Jamal': STYLE_RIGHT_PACE,
    'Faheem Ashraf': STYLE_RIGHT_PACE,
    'Shaheen Shah Afridi': STYLE_LEFT_PACE,
    'Mir Hamza': STYLE_LEFT_PACE,
    'Shadab Khan': STYLE_LEG_SPIN,
    'Usama Mir': STYLE_LEG_SPIN,
    'Abrar Ahmed': STYLE_LEG_SPIN,
    'Mohammad Nawaz': STYLE_SLA,
    'Mohammad Nawaz (3)': STYLE_SLA,
    'Iftikhar Ahmed': STYLE_OFF_SPIN,
    'Agha Salman': STYLE_OFF_SPIN,
    'Aamer Yamin': STYLE_RIGHT_PACE,
    'Akif Javed': STYLE_LEFT_PACE,
    'Asif Ali': STYLE_OFF_SPIN,
    'Azhar Ali': STYLE_LEG_SPIN,
    'Danish Aziz': STYLE_SLA,
    'Faisal Akram': STYLE_LEFT_UNORTHODOX,
    'Fakhar Zaman': STYLE_SLA,
    'Haris Sohail': STYLE_SLA,
    'Hussain Talat': STYLE_RIGHT_PACE,
    'Ihsanullah': STYLE_RIGHT_PACE,
    'Imad Wasim': STYLE_SLA,
    'Irfan Khan': STYLE_OFF_SPIN,
    'Junaid Khan': STYLE_LEFT_PACE,
    'Kamran Ghulam': STYLE_SLA,
    'Khushdil Shah': STYLE_SLA,
    'Mohammad Abbas': STYLE_RIGHT_PACE,
    'Mohammad Ali': STYLE_RIGHT_PACE,
    'Mohammad Amir': STYLE_LEFT_PACE,
    'Mohammad Hafeez': STYLE_OFF_SPIN,
    'Mohammad Hasnain': STYLE_RIGHT_PACE,
    'Mohammad Irfan': STYLE_LEFT_PACE,
    'Muhammad Musa': STYLE_RIGHT_PACE,
    'Rumman Raees': STYLE_LEFT_PACE,
    'Saim Ayub': STYLE_OFF_SPIN,
    'Sarfraz Ahmed': STYLE_OFF_SPIN,
    'Saud Shakeel': STYLE_SLA,
    'Shahnawaz Dhani': STYLE_RIGHT_PACE,
    'Shoaib Malik': STYLE_OFF_SPIN,
    'Sohail Khan': STYLE_RIGHT_PACE,
    'Sufiyan Muqeem': STYLE_LEFT_UNORTHODOX,
    'Umar Amin': STYLE_RIGHT_PACE,
    'Umar Gul': STYLE_RIGHT_PACE,
    'Usman Qadir': STYLE_LEG_SPIN,
    'Usman Shinwari': STYLE_LEFT_PACE,
    'Wahab Riaz': STYLE_LEFT_PACE,
    'Yasir Shah': STYLE_LEG_SPIN,
    'Zahid Mahmood': STYLE_LEG_SPIN,

    # --- SRI LANKA ---
    'PVD Chameera': STYLE_RIGHT_PACE,
    'M Pathirana': STYLE_RIGHT_PACE,
    'CBRLS Kumara': STYLE_RIGHT_PACE,
    'CAK Rajitha': STYLE_RIGHT_PACE,
    'AM Fernando': STYLE_RIGHT_PACE,
    'C Karunaratne': STYLE_RIGHT_PACE,
    'N Thushara': STYLE_RIGHT_PACE,
    'MD Shanaka': STYLE_RIGHT_PACE,
    'D Madushanka': STYLE_LEFT_PACE,
    'PWH de Silva': STYLE_LEG_SPIN,
    'JDF Vandersay': STYLE_LEG_SPIN,
    'M Theekshana': STYLE_OFF_SPIN,
    'DM de Silva': STYLE_OFF_SPIN,
    'KIC Asalanka': STYLE_OFF_SPIN,
    'DN Wellalage': STYLE_SLA,
    'PM Liyanagamage': STYLE_RIGHT_PACE,
    'K Mishara': STYLE_OFF_SPIN,
    'J Liyanage': STYLE_RIGHT_PACE,
    'A Dananjaya': STYLE_LEG_SPIN,
    'AD Mathews': STYLE_RIGHT_PACE,
    'AK Perera': STYLE_SLA,
    'B Fernando': STYLE_LEFT_PACE,
    'BMAJ Mendis': STYLE_SLA,
    'BOP Fernando': STYLE_LEG_SPIN,
    'C Gunasekara': STYLE_LEG_SPIN,
    'C Wickramasinghe': STYLE_RIGHT_PACE,
    'D Lakshan': STYLE_RIGHT_PACE,
    'DAS Gunaratne': STYLE_RIGHT_PACE,
    'DSK Madushanka': STYLE_LEFT_PACE,
    'E Malinga': STYLE_RIGHT_PACE,
    'FDM Karunaratne': STYLE_RIGHT_PACE,
    'GSNFG Jayasuriya': STYLE_SLA,
    'I Udana': STYLE_LEFT_PACE,
    'KMC Bandara': STYLE_LEG_SPIN,
    'KMDN Kulasekara': STYLE_RIGHT_PACE,
    'KNA Bandara': STYLE_LEG_SPIN,
    'LD Madushanka': STYLE_RIGHT_PACE,
    'M Shiraz': STYLE_RIGHT_PACE,
    'MA Aponso': STYLE_SLA,
    'MADI Hemantha': STYLE_LEG_SPIN,
    'MD Gunathilaka': STYLE_OFF_SPIN,
    'MDK Perera': STYLE_OFF_SPIN,
    'MF Maharoof': STYLE_RIGHT_PACE,
    'MNK Fernando': STYLE_RIGHT_PACE,
    'MVT Fernando': STYLE_LEFT_PACE,
    'N Pradeep': STYLE_RIGHT_PACE,
    'NGRP Jayasuriya': STYLE_SLA,
    'NLTC Perera': STYLE_RIGHT_PACE,
    'P Jayawickrama': STYLE_SLA,
    'P Rathnayake': STYLE_RIGHT_PACE,
    'PADLR Sandakan': STYLE_LEFT_UNORTHODOX,
    'PC de Silva': STYLE_OFF_SPIN,
    'PHKD Mendis': STYLE_LEG_SPIN,
    'PLS Gamage': STYLE_RIGHT_PACE,
    'PM Pushpakumara': STYLE_SLA,
    'RAS Lakmal': STYLE_RIGHT_PACE,
    'RMMP Rathnayake': STYLE_RIGHT_PACE,
    'RTM Mendis': STYLE_OFF_SPIN,
    'S Prasanna': STYLE_LEG_SPIN,
    'S Randiv': STYLE_OFF_SPIN,
    'SL Malinga': STYLE_RIGHT_PACE,
    'SS Pathirana': STYLE_SLA,
    'SSD Arachchige': STYLE_OFF_SPIN,
    'TAM Siriwardana': STYLE_SLA,
    'TM Dilshan': STYLE_OFF_SPIN,
    'BKG Mendis': STYLE_LEG_SPIN,
    

    # --- WEST INDIES ---
    'AS Joseph': STYLE_RIGHT_PACE,
    'O Thomas': STYLE_RIGHT_PACE,
    'JNT Seales': STYLE_RIGHT_PACE,
    'S Gabriel': STYLE_RIGHT_PACE,
    'J Holder': STYLE_RIGHT_PACE,
    'JO Holder': STYLE_RIGHT_PACE,
    'R Shepherd': STYLE_RIGHT_PACE,
    'AJ Hosein': STYLE_SLA,
    'G Motie': STYLE_SLA,
    'K Pierre': STYLE_SLA,
    'RL Chase': STYLE_OFF_SPIN,
    'JP Greaves': STYLE_OFF_SPIN,
    'A Athanaze': STYLE_OFF_SPIN,
    'A Phillip': STYLE_RIGHT_PACE,
    'AD Russell': STYLE_RIGHT_PACE,
    'AM McCarthy': STYLE_OFF_SPIN,
    'AR Nurse': STYLE_OFF_SPIN,
    'Akeem Jordan': STYLE_RIGHT_PACE,
    'C Hemraj': STYLE_SLA,
    'CH Gayle': STYLE_OFF_SPIN,
    'CK Holder': STYLE_RIGHT_PACE,
    'CR Brathwaite': STYLE_RIGHT_PACE,
    'D Bishoo': STYLE_LEG_SPIN,
    'DC Drakes': STYLE_RIGHT_PACE,
    'FA Allen': STYLE_SLA,
    'HR Walsh': STYLE_LEG_SPIN,
    'J Blades': STYLE_OFF_SPIN,
    'JD Campbell': STYLE_OFF_SPIN,
    'JE Taylor': STYLE_RIGHT_PACE,
    'JL Carter': STYLE_RIGHT_PACE,
    'JN Mohammed': STYLE_OFF_SPIN,
    'K Sinclair': STYLE_OFF_SPIN,
    'KA Pollard': STYLE_RIGHT_PACE,
    'KAJ Roach': STYLE_RIGHT_PACE,
    'KAR Hodge': STYLE_SLA,
    'KC Brathwaite': STYLE_OFF_SPIN,
    'KJ Harding': STYLE_RIGHT_PACE,
    'KMA Paul': STYLE_RIGHT_PACE,
    'KOK Williams': STYLE_RIGHT_PACE,
    'KR Mayers': STYLE_RIGHT_PACE,
    'KU Carty': STYLE_RIGHT_PACE,
    'MJ Mindley': STYLE_RIGHT_PACE,
    'ML Cummins': STYLE_RIGHT_PACE,
    'MN Samuels': STYLE_OFF_SPIN,
    'MW Forde': STYLE_RIGHT_PACE,
    'NO Miller': STYLE_SLA,
    'OC McCoy': STYLE_LEFT_PACE,
    'OF Smith': STYLE_RIGHT_PACE,
    'R Powell': STYLE_RIGHT_PACE,
    'RA Reifer': STYLE_LEFT_PACE,
    'RR Beaton': STYLE_RIGHT_PACE,
    'S Joseph': STYLE_RIGHT_PACE,
    'SE Rutherford': STYLE_RIGHT_PACE,
    'SH Lewis': STYLE_RIGHT_PACE,
    'SJ Benn': STYLE_SLA,
    'SK Springer': STYLE_RIGHT_PACE,
    'SP Narine': STYLE_OFF_SPIN,
    'SS Cottrell': STYLE_LEFT_PACE,
    'ST Gabriel': STYLE_RIGHT_PACE,
    'V Permaul': STYLE_SLA,
    'Y Cariah': STYLE_LEG_SPIN,

    # --- BANGLADESH ---
    'Taskin Ahmed': STYLE_RIGHT_PACE,
    'Hasan Mahmud': STYLE_RIGHT_PACE,
    'Ebadot Hossain': STYLE_RIGHT_PACE,
    'Tanzim Hasan Sakib': STYLE_RIGHT_PACE,
    'Mustafizur Rahman': STYLE_LEFT_PACE,
    'Shoriful Islam': STYLE_LEFT_PACE,
    'Shakib Al Hasan': STYLE_SLA,
    'Nasum Ahmed': STYLE_SLA,
    'Taijul Islam': STYLE_SLA,
    'Mehedi Hasan Miraz': STYLE_OFF_SPIN,
    'Rishad Hossain': STYLE_LEG_SPIN,
    'Afif Hossain': STYLE_OFF_SPIN,
    'Mahmudullah': STYLE_OFF_SPIN,
    'Mahedi Hasan': STYLE_OFF_SPIN,
    'Mashrafe Mortaza': STYLE_RIGHT_PACE,
    'Mehidy Hasan Miraz': STYLE_OFF_SPIN,
    'Mohammad Saifuddin': STYLE_RIGHT_PACE,
    'Mosaddek Hossain': STYLE_OFF_SPIN,
    'Nayeem Hasan': STYLE_OFF_SPIN,
    'Rubel Hossain': STYLE_RIGHT_PACE,
    'Soumya Sarkar': STYLE_RIGHT_PACE,
    'Sunzamul Islam': STYLE_SLA,

    # --- ZIMBABWE ---
    'B Muzarabani': STYLE_RIGHT_PACE,
    'TL Chatara': STYLE_RIGHT_PACE,
    'R Ngarava': STYLE_LEFT_PACE,
    'LM Jongwe': STYLE_RIGHT_PACE,
    'DT Tiripano': STYLE_RIGHT_PACE,
    'SC Williams': STYLE_SLA,
    'R Burl': STYLE_LEG_SPIN,
    'Sikandar Raza': STYLE_OFF_SPIN,
    'WP Masakadza': STYLE_SLA,
    'A Ndlovu': STYLE_SLA,
    'B Evans': STYLE_RIGHT_PACE,
    'CJ Chibhabha': STYLE_RIGHT_PACE,
    'CT Mumba': STYLE_RIGHT_PACE,
    'F Akram': STYLE_LEFT_PACE,
    'H Masakadza': STYLE_SLA,
    'Innocent Kaia': STYLE_LEG_SPIN,
    'KM Jarvis': STYLE_RIGHT_PACE,
    'M Shumba': STYLE_SLA,
    'N Madziva': STYLE_RIGHT_PACE,
    'T Maruma': STYLE_LEG_SPIN,
    'TS Chisoro': STYLE_SLA,

    # --- IRELAND ---
    'MR Adair': STYLE_RIGHT_PACE,
    'CA Young': STYLE_RIGHT_PACE,
    'B McCarthy': STYLE_RIGHT_PACE,
    'AR McBrine': STYLE_OFF_SPIN,
    'GH Dockrell': STYLE_SLA,
    'GJ Delany': STYLE_LEG_SPIN,
    'SC Getkate': STYLE_RIGHT_PACE,
    'Joshua Little': STYLE_LEFT_PACE,
    'C Campher': STYLE_RIGHT_PACE,
    'F Hand': STYLE_RIGHT_PACE,
    'G Hume': STYLE_RIGHT_PACE,
    'Harry Tector': STYLE_OFF_SPIN,
    'Simi Singh': STYLE_OFF_SPIN,
    'WB Rankin': STYLE_RIGHT_PACE,

    # --- NETHERLANDS ---
    'Logan van Beek': STYLE_RIGHT_PACE,
    'Paul van Meekeren': STYLE_RIGHT_PACE,
    'Bas de Leede': STYLE_RIGHT_PACE,
    'Aryan Dutt': STYLE_OFF_SPIN,
    'Roelof van der Merwe': STYLE_SLA,
    'Shariz Ahmad': STYLE_LEG_SPIN,
    'Fred Klaassen': STYLE_LEFT_PACE,
    'Ryan Klein': STYLE_RIGHT_PACE,
    'Vivian Kingma': STYLE_RIGHT_PACE,
    'Tim Pringle': STYLE_SLA,
    'Brandon Glover': STYLE_RIGHT_PACE,
    'Sikander Zulfiqar': STYLE_RIGHT_PACE,
    'Sybrand Engelbrecht': STYLE_OFF_SPIN,

    # --- 🏛️ HISTORICAL LEGENDS (Pre-2014) ---
    'B Lee': STYLE_RIGHT_PACE,
    'JM Anderson': STYLE_RIGHT_PACE,
    'Shahid Afridi': STYLE_LEG_SPIN,
    'MG Johnson': STYLE_LEFT_PACE,
    'Z Khan': STYLE_LEFT_PACE,
    'M Muralitharan': STYLE_OFF_SPIN,
    'DL Vettori': STYLE_SLA,
    'KD Mills': STYLE_RIGHT_PACE,
    'DJ Bravo': STYLE_RIGHT_PACE,
    'Harbhajan Singh': STYLE_OFF_SPIN,
    'Saeed Ajmal': STYLE_OFF_SPIN,
    'Abdur Razzak': STYLE_SLA,
    'NW Bracken': STYLE_LEFT_PACE,
    'SR Watson': STYLE_RIGHT_PACE,
    'IK Pathan': STYLE_LEFT_PACE,
    'M Ntini': STYLE_RIGHT_PACE,
    'BAW Mendis': STYLE_OFF_SPIN,
    'GB Hogg': STYLE_LEFT_UNORTHODOX,
    'A Flintoff': STYLE_RIGHT_PACE,
    'JDP Oram': STYLE_RIGHT_PACE,
    'I Sharma': STYLE_RIGHT_PACE,
    'WPUJC Vaas': STYLE_LEFT_PACE,
    'SM Pollock': STYLE_RIGHT_PACE,
    'TT Bresnan': STYLE_RIGHT_PACE,
    'CRD Fernando': STYLE_RIGHT_PACE,
    'A Nehra': STYLE_LEFT_PACE,
    'R Rampaul': STYLE_RIGHT_PACE,
    'SE Bond': STYLE_RIGHT_PACE,
    'Abdul Razzaq': STYLE_RIGHT_PACE,
    'GD McGrath': STYLE_RIGHT_PACE,
    'GP Swann': STYLE_OFF_SPIN,
    'AB Agarkar': STYLE_RIGHT_PACE,
    'ST Jayasuriya': STYLE_SLA,
    'CJ McKay': STYLE_RIGHT_PACE,
    'P Utseya': STYLE_OFF_SPIN,
    'Shoaib Akhtar': STYLE_RIGHT_PACE,
    'JH Kallis': STYLE_RIGHT_PACE,
    'SM Sharif': STYLE_RIGHT_PACE,
    'LL Tsotsobe': STYLE_LEFT_PACE,
    'Naved-ul-Hasan': STYLE_RIGHT_PACE,
    'PD Collingwood': STYLE_RIGHT_PACE,
    'A Nel': STYLE_RIGHT_PACE,
    'MM Patel': STYLE_RIGHT_PACE,
    'Junaid Siddique': STYLE_RIGHT_PACE,
    'MJ McClenaghan': STYLE_LEFT_PACE,
    'E Chigumbura': STYLE_RIGHT_PACE,
    'CK Langeveldt': STYLE_RIGHT_PACE,
    'DJG Sammy': STYLE_RIGHT_PACE,
    'RW Price': STYLE_SLA,
    'P Kumar': STYLE_RIGHT_PACE,
    'AJ Hall': STYLE_RIGHT_PACE,
    'R McLaren': STYLE_RIGHT_PACE,
    'A Symonds': STYLE_OFF_SPIN,
    'S Sreesanth': STYLE_RIGHT_PACE,
    'HMRKB Herath': STYLE_SLA,
    'J Botha': STYLE_OFF_SPIN,
    'SB Styris': STYLE_RIGHT_PACE,
    'RJ Peterson': STYLE_SLA,
    'AG Cremer': STYLE_LEG_SPIN,
    'Sohail Tanvir': STYLE_LEFT_PACE,
    'RP Singh': STYLE_LEFT_PACE,
    'JR Hopes': STYLE_RIGHT_PACE,
    'Shafiul Islam': STYLE_RIGHT_PACE,
    'Iftikhar Anjum': STYLE_RIGHT_PACE,
    'Mohammad Sami': STYLE_RIGHT_PACE,
    'NL McCullum': STYLE_OFF_SPIN,
    'IDR Bradshaw': STYLE_LEFT_PACE,
    'CB Mpofu': STYLE_RIGHT_PACE,
    'SJ Harmison': STYLE_RIGHT_PACE,
    'SW Tait': STYLE_RIGHT_PACE,
    'DE Bollinger': STYLE_LEFT_PACE,
    'XJ Doherty': STYLE_SLA,
    'JC Tredwell': STYLE_OFF_SPIN,
    'KJ O\'Brien': STYLE_RIGHT_PACE,
    'T Panyangara': STYLE_RIGHT_PACE,
    'SMSM Senanayake': STYLE_OFF_SPIN,
    'JN Gillespie': STYLE_RIGHT_PACE,
    'V Sehwag': STYLE_OFF_SPIN,
    'JEC Franklin': STYLE_LEFT_PACE,
    'D Gough': STYLE_RIGHT_PACE,
    'MJ Clarke': STYLE_SLA,
    'NM Hauritz': STYLE_OFF_SPIN,
    'Mohammad Rafique': STYLE_SLA,
    'DR Smith': STYLE_RIGHT_PACE,
    'FH Edwards': STYLE_RIGHT_PACE,
    'Syed Rasel': STYLE_LEFT_PACE,
    'DBL Powell': STYLE_RIGHT_PACE,
    'DR Tuffey': STYLE_RIGHT_PACE,
    'SR Clark': STYLE_RIGHT_PACE,
    'JA Morkel': STYLE_RIGHT_PACE,
    'T Thushara': STYLE_LEFT_PACE,
    'TJ Murtagh': STYLE_RIGHT_PACE,
    'RE van der Merwe': STYLE_SLA,
    'R Vinay Kumar': STYLE_RIGHT_PACE,
    'RJ Harris': STYLE_RIGHT_PACE,
    'TM Odoyo': STYLE_RIGHT_PACE,
    'HH Streak': STYLE_RIGHT_PACE,
    'VD Philander': STYLE_RIGHT_PACE,
    'RS Bopara': STYLE_RIGHT_PACE,
    'SK Warne': STYLE_LEG_SPIN,
    'AF Giles': STYLE_SLA,
    'Mohammad Asif': STYLE_RIGHT_PACE,
    'DT Johnston': STYLE_RIGHT_PACE,
    'T Mupariwa': STYLE_RIGHT_PACE,
    'GD Elliott': STYLE_RIGHT_PACE,
    'UDU Chandana': STYLE_LEG_SPIN,
    'SI Mahmood': STYLE_RIGHT_PACE,
    'YK Pathan': STYLE_OFF_SPIN,
    'JF Mooney': STYLE_RIGHT_PACE,
    'MS Kasprowicz': STYLE_RIGHT_PACE,
    'TL Best': STYLE_RIGHT_PACE,
    'CD Collymore': STYLE_RIGHT_PACE,
    'Abdur Rehman': STYLE_SLA,
    'Naeem Islam': STYLE_OFF_SPIN,
    'PJ Ongondo': STYLE_RIGHT_PACE,
    'AR Cusack': STYLE_RIGHT_PACE,
    'MM Sharma': STYLE_RIGHT_PACE,
    'BA Williams': STYLE_RIGHT_PACE,
    'RR Powar': STYLE_OFF_SPIN,
    'AJ Bichel': STYLE_RIGHT_PACE,
    'BW Hilfenhaus': STYLE_RIGHT_PACE,
    'PP Chawla': STYLE_LEG_SPIN,
    'BV Vitori': STYLE_LEFT_PACE,
    'DT Hondo': STYLE_RIGHT_PACE,
    'A Kumble': STYLE_LEG_SPIN,
    'J Theron': STYLE_RIGHT_PACE,
    'SR Tendulkar': STYLE_OFF_SPIN,
    'MR Gillespie': STYLE_RIGHT_PACE,
    'JW Dernbach': STYLE_RIGHT_PACE,
    'KTGD Prasad': STYLE_RIGHT_PACE,
    'AM Blignaut': STYLE_LEFT_PACE,
    'MS Panesar': STYLE_SLA,
    'Nazmul Hossain': STYLE_RIGHT_PACE,
    'HMCM Bandara': STYLE_LEG_SPIN,
    'M Kartik': STYLE_SLA,
    'IJ Harvey': STYLE_RIGHT_PACE,
    'Shahadat Hossain': STYLE_RIGHT_PACE,
    'SO Tikolo': STYLE_OFF_SPIN,
    'Tapash Baisya': STYLE_RIGHT_PACE,
    'L Balaji': STYLE_RIGHT_PACE,
    'AJ McKay': STYLE_RIGHT_PACE,
    'AR Adams': STYLE_RIGHT_PACE,
    'J Srinath': STYLE_RIGHT_PACE,
    'MJ Mason': STYLE_RIGHT_PACE,
    'RM Haq': STYLE_OFF_SPIN,
    'JH Davey': STYLE_RIGHT_PACE,
    'PR Stirling': STYLE_OFF_SPIN,
    'PM Seelaar': STYLE_SLA,
    'Nadeem Ahmed': STYLE_SLA,
    'Nasir Hossain': STYLE_OFF_SPIN,
    'GB Brent': STYLE_RIGHT_PACE,
    'RJ Sidebottom': STYLE_LEFT_PACE,
    'M Dillon': STYLE_RIGHT_PACE,
    'SM Ervine': STYLE_RIGHT_PACE,
    'H Osinde': STYLE_RIGHT_PACE,
    'HS Baidwan': STYLE_RIGHT_PACE,
    'Khaled Mahmud': STYLE_RIGHT_PACE,
    'NN Odhiambo': STYLE_RIGHT_PACE,
    'Sohag Gazi': STYLE_OFF_SPIN,
    'DNT Zoysa': STYLE_LEFT_PACE,
    'Aizaz Cheema': STYLE_RIGHT_PACE,
    'SW Masakadza': STYLE_RIGHT_PACE,
    'SC Ganguly': STYLE_RIGHT_PACE,
    'SR Patel': STYLE_SLA,
    'S Dhaniram': STYLE_SLA,
    'DS Lehmann': STYLE_SLA,
    'WW Hinds': STYLE_RIGHT_PACE,
    'RMS Eranga': STYLE_RIGHT_PACE,
    'CO Obuya': STYLE_LEG_SPIN,
    'DT Christian': STYLE_RIGHT_PACE,
    'PP Ojha': STYLE_SLA,
    'Kabir Ali': STYLE_RIGHT_PACE,
    'MH Yardy': STYLE_SLA,
    'CL Cairns': STYLE_RIGHT_PACE,
    'Anwar Ali': STYLE_RIGHT_PACE,
    'N Boje': STYLE_SLA,
    'RN ten Doeschate': STYLE_RIGHT_PACE,
    'Rahat Ali': STYLE_LEFT_PACE,
    'Khurram Chohan': STYLE_RIGHT_PACE,
    'DJ Hussey': STYLE_OFF_SPIN,
    'GC Smith': STYLE_OFF_SPIN,
    'JM Davison': STYLE_OFF_SPIN,
    'JJ van der Wath': STYLE_RIGHT_PACE,
    'Alok Kapali': STYLE_LEG_SPIN,
    'HA Varaiya': STYLE_SLA,
    'Shabbir Ahmed': STYLE_RIGHT_PACE,
    'KS Lokuarachchi': STYLE_LEG_SPIN,
    'AG Wharf': STYLE_RIGHT_PACE,
    'I Wardlaw': STYLE_RIGHT_PACE,
    'VC Drakes': STYLE_RIGHT_PACE,
    'AR Caddick': STYLE_RIGHT_PACE,
    'TBM de Leede': STYLE_RIGHT_PACE,
    'LJ Wright': STYLE_RIGHT_PACE,
    'JM Kemp': STYLE_RIGHT_PACE,
    'EC Rainsford': STYLE_RIGHT_PACE,
    'Suhrawadi Shuvo': STYLE_SLA,
    'J Lewis': STYLE_RIGHT_PACE,
    'KAD Hurdle': STYLE_RIGHT_PACE,
    'UWMBCA Welegedara': STYLE_LEFT_PACE,
    'RR Sarwan': STYLE_LEG_SPIN,
}

# --- PLAYER ROLE CONSTANTS ---
ROLE_BATTER = 'Batter'
ROLE_BOWLER = 'Bowler'
ROLE_BAT_AR = 'Batting All-Rounder'
ROLE_BOWL_AR = 'Bowling All-Rounder'
# ROLE_WK = 'Wicket Keeper'  <-- DELETED

# --- PLAYER ROLES MAPPING ---
PLAYER_ROLES = {

    # --- ENGLAND ---
    'JE Root': ROLE_BATTER,
    'HC Brook': ROLE_BATTER,
    'BM Duckett': ROLE_BATTER,
    'Z Crawley': ROLE_BATTER,
    'JC Buttler': ROLE_BATTER, 
    'JM Bairstow': ROLE_BATTER,
    'PD Salt': ROLE_BATTER,
    'BA Stokes': ROLE_BAT_AR,
    'LS Livingstone': ROLE_BAT_AR,
    'JG Bethell': ROLE_BAT_AR,
    'MM Ali': ROLE_BOWL_AR,
    'SM Curran': ROLE_BOWL_AR,
    'LA Dawson': ROLE_BOWL_AR, 
    'AU Rashid': ROLE_BOWLER,
    'MA Wood': ROLE_BOWLER,
    'J Archer': ROLE_BOWLER,
    'J Overton': ROLE_BOWLER,
    'Rehan Ahmed': ROLE_BOWLER,
    'AAP Atkinson': ROLE_BOWLER,
    'AD Hales': ROLE_BATTER,
    'BA Carse': ROLE_BOWLER,
    'BT Foakes': ROLE_BATTER,
    'C Overton': ROLE_BOWL_AR,
    'CJ Jordan': ROLE_BOWLER,
    'CR Woakes': ROLE_BOWL_AR,
    'DA Payne': ROLE_BOWLER,
    'DJ Malan': ROLE_BATTER,
    'DJ Willey': ROLE_BOWL_AR,
    'DR Mousley': ROLE_BAT_AR,
    'EJG Morgan': ROLE_BATTER,
    'GLS Scrimshaw': ROLE_BOWLER,
    'JA Simpson': ROLE_BATTER,
    'JA Turner': ROLE_BOWLER,
    'JC Archer': ROLE_BOWLER,
    'JJ Roy': ROLE_BATTER,
    'JL Denly': ROLE_BAT_AR,
    'JL Smith': ROLE_BATTER,
    'JM Cox': ROLE_BATTER,
    'JM Vince': ROLE_BATTER,
    'JT Ball': ROLE_BOWLER,
    'L Gregory': ROLE_BOWL_AR,
    'L Wood': ROLE_BOWLER,
    'LE Plunkett': ROLE_BOWLER,
    'MJ Potts': ROLE_BOWLER,
    'MW Parkinson': ROLE_BOWLER,
    'OP Stone': ROLE_BOWLER,
    'RJW Topley': ROLE_BOWLER,
    'S Baker': ROLE_BOWLER,
    'S Mahmood': ROLE_BOWLER,
    'SCJ Broad': ROLE_BOWLER,
    'SR Hain': ROLE_BATTER,
    'ST Finn': ROLE_BOWLER,
    'SW Billings': ROLE_BATTER,
    'T Banton': ROLE_BATTER,
    'TK Curran': ROLE_BOWL_AR,
    'TS Roland-Jones': ROLE_BOWLER,
    'TW Hartley': ROLE_BOWLER,
    'WG Jacks': ROLE_BAT_AR,

    # --- AUSTRALIA ---
    'A Zampa': ROLE_BOWLER,
    'AC Agar': ROLE_BOWL_AR,
    'AJ Finch': ROLE_BATTER,
    'AJ Turner': ROLE_BAT_AR,
    'AJ Tye': ROLE_BOWLER,
    'AM Hardie': ROLE_BOWL_AR,
    'AT Carey': ROLE_BATTER,
    'B Stanlake': ROLE_BOWLER,
    'BJ Dwarshuis': ROLE_BOWLER,
    'BR McDermott': ROLE_BATTER,
    'C Connolly': ROLE_BAT_AR,
    'C Green': ROLE_BOWL_AR,
    'CA Lynn': ROLE_BATTER,
    'CL White': ROLE_BATTER,
    'CP Tremain': ROLE_BOWLER,
    'DA Warner': ROLE_BATTER,
    'DJ Worrall': ROLE_BOWLER,
    'DJM Short': ROLE_BATTER,
    'GJ Bailey': ROLE_BATTER,
    'GJ Maxwell': ROLE_BAT_AR,
    'HWR Cartwright': ROLE_BATTER,
    'J Fraser-McGurk': ROLE_BATTER,
    'JA Richardson': ROLE_BOWLER,
    'JM Mennie': ROLE_BOWLER,
    'JP Behrendorff': ROLE_BOWLER,
    'JP Faulkner': ROLE_BOWL_AR,
    'JP Inglis': ROLE_BATTER,
    'JR Hazlewood': ROLE_BOWLER,
    'JR Philippe': ROLE_BATTER,
    'JW Hastings': ROLE_BOWL_AR,
    'KW Richardson': ROLE_BOWLER,
    'LR Morris': ROLE_BOWLER,
    'M Labuschagne': ROLE_BATTER,
    'MA Starc': ROLE_BOWLER,
    'MC Henriques': ROLE_BOWL_AR,
    'MG Neser': ROLE_BOWLER,
    'MJ Owen': ROLE_BATTER,
    'MJ Swepson': ROLE_BOWLER,
    'MP Kuhnemann': ROLE_BOWLER,
    'MP Stoinis': ROLE_BOWL_AR,
    'MR Marsh': ROLE_BAT_AR,
    'MS Wade': ROLE_BATTER,
    'MT Renshaw': ROLE_BATTER,
    'MW Short': ROLE_BAT_AR,
    'NM Coulter-Nile': ROLE_BOWLER,
    'NM Lyon': ROLE_BOWLER,
    'NT Ellis': ROLE_BOWLER,
    'PJ Cummins': ROLE_BOWLER,
    'PM Siddle': ROLE_BOWLER,
    'PSP Handscomb': ROLE_BATTER,
    'RP Meredith': ROLE_BOWLER,
    'SA Abbott': ROLE_BOWL_AR,
    'SD Heazlett': ROLE_BATTER,
    'SE Marsh': ROLE_BATTER,
    'SH Johnson': ROLE_BOWLER,
    'SM Boland': ROLE_BOWLER,
    'SPD Smith': ROLE_BATTER,
    'T Sangha': ROLE_BOWLER,
    'TD Paine': ROLE_BATTER,
    'TH David': ROLE_BATTER,
    'TM Head': ROLE_BATTER,
    'UT Khawaja': ROLE_BATTER,
    'W Sutherland': ROLE_BOWL_AR,
    'WA Agar': ROLE_BOWLER,
    'XC Bartlett': ROLE_BOWLER,

    # --- SOUTH AFRICA ---
    'K Rabada': ROLE_BOWLER,
    'A Nortje': ROLE_BOWLER,
    'G Coetzee': ROLE_BOWLER,
    'L Ngidi': ROLE_BOWLER,
    'OEG Baartman': ROLE_BOWLER,
    'AL Phehlukwayo': ROLE_BOWL_AR,
    'PWA Mulder': ROLE_BOWL_AR,
    'M Jansen': ROLE_BOWL_AR,
    'N Burger': ROLE_BOWLER,
    'KA Maharaj': ROLE_BOWLER,
    'BC Fortuin': ROLE_BOWLER,
    'T Shamsi': ROLE_BOWLER,
    'AB de Villiers': ROLE_BATTER,
    'AK Markram': ROLE_BAT_AR,
    'AM Phangiso': ROLE_BOWLER,
    'BE Hendricks': ROLE_BOWLER,
    'C Bosch': ROLE_BOWL_AR,
    'C Jonker': ROLE_BATTER,
    'CH Morris': ROLE_BOWL_AR,
    'CJ Dala': ROLE_BOWLER,
    'Codi Yusuf': ROLE_BOWLER,
    'D Brevis': ROLE_BATTER,
    'D Elgar': ROLE_BATTER,
    'D Ferreira': ROLE_BAT_AR,
    'D Olivier': ROLE_BOWLER,
    'D Paterson': ROLE_BOWLER,
    'D Pretorius': ROLE_BOWL_AR,
    'D Wiese': ROLE_BOWL_AR,
    'DA Miller': ROLE_BATTER,
    'DM Dupavillon': ROLE_BOWLER,
    'DW Steyn': ROLE_BOWLER,
    'E Bosch': ROLE_BOWL_AR,
    'F Behardien': ROLE_BAT_AR,
    'F du Plessis': ROLE_BATTER,
    'GF Linde': ROLE_BOWL_AR,
    'H Klaasen': ROLE_BATTER,
    'HE van der Dussen': ROLE_BATTER,
    'HM Amla': ROLE_BATTER,
    'Imran Tahir': ROLE_BOWLER,
    'JF Smith': ROLE_BOWL_AR,
    'JN Malan': ROLE_BATTER,
    'JP Duminy': ROLE_BAT_AR,
    'JT Smuts': ROLE_BAT_AR,
    'K Verreynne': ROLE_BATTER,
    'K Zondo': ROLE_BATTER,
    'KJ Abbott': ROLE_BOWLER,
    'KT Maphaka': ROLE_BOWLER,
    'L Sipamla': ROLE_BOWLER,
    'LB Williams': ROLE_BOWLER,
    'LG Pretorius': ROLE_BATTER,
    'M Morkel': ROLE_BOWLER,
    'M Mpongwana': ROLE_BOWL_AR,
    'MP Breetzke': ROLE_BATTER,
    'N Peter': ROLE_BOWLER,
    'P Subrayen': ROLE_BOWLER,
    'Q de Kock': ROLE_BATTER,
    'RA Herman': ROLE_BATTER,
    'RD Rickelton': ROLE_BATTER,
    'RR Hendricks': ROLE_BATTER,
    'RR Rossouw': ROLE_BATTER,
    'S Muthusamy': ROLE_BOWL_AR,
    'S Qeshile': ROLE_BATTER,
    'SSB Magala': ROLE_BOWLER,
    'T Bavuma': ROLE_BATTER,
    'T Stubbs': ROLE_BATTER,
    'T de Zorzi': ROLE_BATTER,
    'WD Parnell': ROLE_BOWL_AR,
    'Zubayr Hamza': ROLE_BATTER,

    # --- NEW ZEALAND ---
    'TG Southee': ROLE_BOWLER,
    'MJ Henry': ROLE_BOWLER,
    'LH Ferguson': ROLE_BOWLER,
    'AF Milne': ROLE_BOWLER,
    'KA Jamieson': ROLE_BOWLER,
    'BV Sears': ROLE_BOWLER,
    'W O\'Rourke': ROLE_BOWLER,
    'TA Boult': ROLE_BOWLER,
    'MJ Santner': ROLE_BOWL_AR,
    'R Ravindra': ROLE_BAT_AR,
    'IS Sodhi': ROLE_BOWLER,
    'GD Phillips': ROLE_BATTER,
    'MG Bracewell': ROLE_BAT_AR,
    'DJ Mitchell': ROLE_BAT_AR,
    'JR Lennox': ROLE_BOWLER,
    'A Ashok': ROLE_BOWLER,
    'AP Devcich': ROLE_BAT_AR,
    'BG Lister': ROLE_BOWLER,
    'BJ Watling': ROLE_BATTER,
    'BM Tickner': ROLE_BOWLER,
    'C Munro': ROLE_BATTER,
    'C de Grandhomme': ROLE_BOWL_AR,
    'CE McConchie': ROLE_BAT_AR,
    'CJ Anderson': ROLE_BOWL_AR,
    'CJ Bowes': ROLE_BATTER,
    'D Cleaver': ROLE_BATTER,
    'D Foxcroft': ROLE_BATTER,
    'DAJ Bracewell': ROLE_BOWL_AR,
    'DG Brownlie': ROLE_BATTER,
    'DP Conway': ROLE_BATTER,
    'FH Allen': ROLE_BATTER,
    'GH Worker': ROLE_BATTER,
    'HB Shipley': ROLE_BOWLER,
    'HK Bennett': ROLE_BOWLER,
    'HM Nicholls': ROLE_BATTER,
    'JA Clarkson': ROLE_BOWL_AR,
    'JA Duffy': ROLE_BOWLER,
    'JDS Neesham': ROLE_BOWL_AR,
    'JS Patel': ROLE_BOWLER,
    'KDC Clarke': ROLE_BATTER,
    'KS Williamson': ROLE_BATTER,
    'L Ronchi': ROLE_BATTER,
    'LRPL Taylor': ROLE_BATTER,
    'MA Abbas': ROLE_BOWLER,
    'MJ Guptill': ROLE_BATTER,
    'MJ Hay': ROLE_BATTER,
    'MS Chapman': ROLE_BATTER,
    'NF Kelly': ROLE_BATTER,
    'NG Smith': ROLE_BOWL_AR,
    'NT Broom': ROLE_BATTER,
    'R Ravindra': ROLE_BAT_AR,  # Included twice in previous plan, fixed
    'RA Mariu': ROLE_BATTER,
    'SC Kuggeleijn': ROLE_BOWL_AR,
    'SHA Rance': ROLE_BOWLER,
    'TA Blundell': ROLE_BATTER,
    'TB Robinson': ROLE_BATTER,
    'TD Astle': ROLE_BOWLER,
    'TL Seifert': ROLE_BATTER,
    'TWM Latham': ROLE_BATTER,
    'WA Young': ROLE_BATTER,
    'ZGF Foulkes': ROLE_BOWLER,

    # --- INDIA ---
    'MS Dhoni': ROLE_BATTER,
    'V Kohli': ROLE_BATTER,
    'RG Sharma': ROLE_BATTER,
    'S Dhawan': ROLE_BATTER,
    'KL Rahul': ROLE_BATTER,
    'RR Pant': ROLE_BATTER,
    'SS Iyer': ROLE_BATTER,
    'SA Yadav': ROLE_BATTER,
    'Shubman Gill': ROLE_BATTER,
    'Ishan Kishan': ROLE_BATTER,
    'SV Samson': ROLE_BATTER,
    'AM Rahane': ROLE_BATTER,
    'AT Rayudu': ROLE_BATTER,
    'MK Pandey': ROLE_BATTER,
    'KD Karthik': ROLE_BATTER,
    'SK Raina': ROLE_BAT_AR,
    'Yuvraj Singh': ROLE_BAT_AR,
    'KM Jadhav': ROLE_BAT_AR,
    'HH Pandya': ROLE_BOWL_AR,
    'RA Jadeja': ROLE_BOWL_AR,
    'R Ashwin': ROLE_BOWL_AR,
    'AR Patel': ROLE_BOWL_AR,
    'SN Thakur': ROLE_BOWL_AR,
    'DL Chahar': ROLE_BOWL_AR,
    'KH Pandya': ROLE_BOWL_AR,
    'Washington Sundar': ROLE_BOWL_AR,
    'Shahbaz Ahmed': ROLE_BOWL_AR,
    'DJ Hooda': ROLE_BAT_AR,
    'V Shankar': ROLE_BAT_AR,
    'VR Iyer': ROLE_BAT_AR,
    'S Dube': ROLE_BAT_AR,
    'N Rana': ROLE_BAT_AR,
    'R Parag': ROLE_BAT_AR,
    'Tilak Varma': ROLE_BAT_AR,
    'Nithish Kumar Reddy': ROLE_BOWL_AR,
    'JJ Bumrah': ROLE_BOWLER,
    'Mohammed Shami': ROLE_BOWLER,
    'Mohammed Siraj': ROLE_BOWLER,
    'B Kumar': ROLE_BOWLER,
    'YS Chahal': ROLE_BOWLER,
    'Kuldeep Yadav': ROLE_BOWLER,
    'Ravi Bishnoi': ROLE_BOWLER,
    'A Mishra': ROLE_BOWLER,
    'RD Chahar': ROLE_BOWLER,
    'UT Yadav': ROLE_BOWLER,
    'Umran Malik': ROLE_BOWLER,
    'Navdeep Saini': ROLE_BOWLER,
    'T Natarajan': ROLE_BOWLER,
    'KK Ahmed': ROLE_BOWLER,
    'JD Unadkat': ROLE_BOWLER,
    'M Prasidh Krishna': ROLE_BOWLER,
    'Arshdeep Singh': ROLE_BOWLER,
    'Harshit Rana': ROLE_BOWLER,
    'Mukesh Kumar': ROLE_BOWLER,
    'Avesh Khan': ROLE_BOWLER,
    'KR Sen': ROLE_BOWLER,
    'RD Gaikwad': ROLE_BATTER,
    'YBK Jaiswal': ROLE_BATTER,
    'RK Singh': ROLE_BATTER,
    'RM Patidar': ROLE_BATTER,
    'B Sai Sudharsan': ROLE_BATTER,
    'PP Shaw': ROLE_BATTER,
    'MA Agarwal': ROLE_BATTER,
    'FY Fazal': ROLE_BATTER,
    'KK Nair': ROLE_BATTER,
    'K Gowtham': ROLE_BOWLER,
    'J Yadav': ROLE_BOWLER,
    'DS Kulkarni': ROLE_BOWLER,
    'S Kaul': ROLE_BOWLER,
    'C Sakariya': ROLE_BOWLER,
    'BB Sran': ROLE_BOWLER,
    'CV Varun': ROLE_BOWLER,

    # --- PAKISTAN ---
    'Aamer Jamal': ROLE_BOWL_AR,
    'Aamer Yamin': ROLE_BOWL_AR,
    'Abdullah Shafique': ROLE_BATTER,
    'Abid Ali': ROLE_BATTER,
    'Abrar Ahmed': ROLE_BOWLER,
    'Agha Salman': ROLE_BAT_AR,
    'Ahmed Shehzad': ROLE_BATTER,
    'Akif Javed': ROLE_BOWLER,
    'Asad Shafiq': ROLE_BATTER,
    'Asif Ali': ROLE_BATTER,
    'Azhar Ali': ROLE_BATTER,
    'Babar Azam': ROLE_BATTER,
    'Danish Aziz': ROLE_BAT_AR,
    'Faheem Ashraf': ROLE_BOWL_AR,
    'Faisal Akram': ROLE_BOWLER,
    'Fakhar Zaman': ROLE_BATTER,
    'Haider Ali': ROLE_BATTER,
    'Haris Rauf': ROLE_BOWLER,
    'Haris Sohail': ROLE_BATTER,
    'Hasan Ali': ROLE_BOWLER,
    'Haseebullah Khan': ROLE_BATTER,
    'Hassan Nawaz': ROLE_BATTER,
    'Hussain Talat': ROLE_BAT_AR,
    'Iftikhar Ahmed': ROLE_BAT_AR,
    'Ihsanullah': ROLE_BOWLER,
    'Imad Wasim': ROLE_BOWL_AR,
    'Imam-ul-Haq': ROLE_BATTER,
    'Irfan Khan': ROLE_BATTER,
    'Junaid Khan': ROLE_BOWLER,
    'Kamran Akmal': ROLE_BATTER,
    'Kamran Ghulam': ROLE_BAT_AR,
    'Khushdil Shah': ROLE_BAT_AR,
    'Mohammad Abbas': ROLE_BOWLER,
    'Mohammad Ali': ROLE_BOWLER,
    'Mohammad Amir': ROLE_BOWLER,
    'Mohammad Hafeez': ROLE_BAT_AR,
    'Mohammad Haris': ROLE_BATTER,
    'Mohammad Hasnain': ROLE_BOWLER,
    'Mohammad Irfan': ROLE_BOWLER,
    'Mohammad Nawaz': ROLE_BOWL_AR,
    'Mohammad Nawaz (3)': ROLE_BOWL_AR,
    'Mohammad Rizwan': ROLE_BATTER,
    'Mohammad Wasim': ROLE_BOWL_AR,
    'Muhammad Musa': ROLE_BOWLER,
    'Naseem Shah': ROLE_BOWLER,
    'Rumman Raees': ROLE_BOWLER,
    'Saad Ali': ROLE_BATTER,
    'Saim Ayub': ROLE_BATTER,
    'Sami Aslam': ROLE_BATTER,
    'Sarfraz Ahmed': ROLE_BATTER,
    'Saud Shakeel': ROLE_BATTER,
    'Shadab Khan': ROLE_BOWL_AR,
    'Shaheen Shah Afridi': ROLE_BOWLER,
    'Shahnawaz Dhani': ROLE_BOWLER,
    'Shan Masood': ROLE_BATTER,
    'Sharjeel Khan': ROLE_BATTER,
    'Shoaib Malik': ROLE_BAT_AR,
    'Sohaib Maqsood': ROLE_BATTER,
    'Sohail Khan': ROLE_BOWLER,
    'Sufiyan Muqeem': ROLE_BOWLER,
    'Tayyab Tahir': ROLE_BATTER,
    'Umar Akmal': ROLE_BATTER,
    'Umar Amin': ROLE_BATTER,
    'Umar Gul': ROLE_BOWLER,
    'Usama Mir': ROLE_BOWLER,
    'Usman Khan': ROLE_BATTER,
    'Usman Khan (2)': ROLE_BATTER,
    'Usman Qadir': ROLE_BOWLER,
    'Usman Shinwari': ROLE_BOWLER,
    'Wahab Riaz': ROLE_BOWLER,
    'Yasir Shah': ROLE_BOWLER,
    'Zahid Mahmood': ROLE_BOWLER,
    'Zaman Khan': ROLE_BOWLER,

    # --- SRI LANKA ---
    'A Dananjaya': ROLE_BOWLER,
    'AD Mathews': ROLE_BAT_AR,
    'AK Perera': ROLE_BAT_AR,
    'B Fernando': ROLE_BOWLER,
    'BMAJ Mendis': ROLE_BOWL_AR,
    'BOP Fernando': ROLE_BATTER,
    'C Gunasekara': ROLE_BATTER,
    'C Karunaratne': ROLE_BOWL_AR,
    'C Wickramasinghe': ROLE_BOWL_AR,
    'CAK Rajitha': ROLE_BOWLER,
    'CBRLS Kumara': ROLE_BOWLER,
    'CK Kapugedera': ROLE_BATTER,
    'D Lakshan': ROLE_BOWL_AR,
    'D Madushanka': ROLE_BOWLER,
    'DAS Gunaratne': ROLE_BAT_AR,
    'DS Weerakkody': ROLE_BATTER,
    'DSK Madushanka': ROLE_BOWLER,
    'E Malinga': ROLE_BOWLER,
    'EMDY Munaweera': ROLE_BATTER,
    'FDM Karunaratne': ROLE_BATTER,
    'GSNFG Jayasuriya': ROLE_BATTER,
    'HDRL Thirimanne': ROLE_BATTER,
    'I Udana': ROLE_BOWL_AR,
    'KMC Bandara': ROLE_BOWLER,
    'KMDN Kulasekara': ROLE_BOWLER,
    'KNA Bandara': ROLE_BOWLER,
    'KNM Fernando': ROLE_BATTER,
    'LD Chandimal': ROLE_BATTER,
    'LD Madushanka': ROLE_BOWL_AR,
    'M Bhanuka': ROLE_BATTER,
    'M Shiraz': ROLE_BOWLER,
    'M Theekshana': ROLE_BOWLER,
    'MA Aponso': ROLE_BOWLER,
    'MADI Hemantha': ROLE_BOWLER,
    'MD Gunathilaka': ROLE_BATTER,
    'MD Shanaka': ROLE_BOWL_AR,
    'MDK Perera': ROLE_BOWL_AR,
    'MDKJ Perera': ROLE_BATTER,
    'MF Maharoof': ROLE_BOWL_AR,
    'MNK Fernando': ROLE_BOWL_AR,
    'MVT Fernando': ROLE_BOWLER,
    'N Dickwella': ROLE_BATTER,
    'N Pradeep': ROLE_BOWLER,
    'NGRP Jayasuriya': ROLE_BOWLER,
    'NLTC Perera': ROLE_BOWL_AR,
    'P Jayawickrama': ROLE_BOWLER,
    'PADLR Sandakan': ROLE_BOWLER,
    'PARP Perera': ROLE_BATTER,
    'PBB Rajapaksa': ROLE_BATTER,
    'PC de Silva': ROLE_BOWL_AR,
    'PHKD Mendis': ROLE_BATTER,
    'PLS Gamage': ROLE_BOWLER,
    'PM Pushpakumara': ROLE_BOWLER,
    'PVD Chameera': ROLE_BOWLER,
    'RAS Lakmal': ROLE_BOWLER,
    'RMMP Rathnayake': ROLE_BOWLER,
    'RMS Eranga': ROLE_BOWLER,
    'RTM Mendis': ROLE_BOWL_AR,
    'S Daniel': ROLE_BATTER,
    'S Prasanna': ROLE_BOWL_AR,
    'S Randiv': ROLE_BOWLER,
    'S Samarawickrama': ROLE_BATTER,
    'SL Malinga': ROLE_BOWLER,
    'SS Pathirana': ROLE_BOWL_AR,
    'SSD Arachchige': ROLE_BAT_AR,
    'TAM Siriwardana': ROLE_BAT_AR,
    'TM Dilshan': ROLE_BATTER,
    'WIA Fernando': ROLE_BATTER,
    'WU Tharanga': ROLE_BATTER,
    'P Nissanka': ROLE_BATTER,
    'BKG Mendis': ROLE_BATTER,
    'K Mishara': ROLE_BATTER,

    # --- WEST INDIES ---
    'A Athanaze': ROLE_BATTER,
    'A Phillip': ROLE_BOWLER,
    'AD Russell': ROLE_BOWL_AR,
    'ADS Fletcher': ROLE_BATTER,
    'AM McCarthy': ROLE_BATTER,
    'AR Nurse': ROLE_BOWL_AR,
    'Akeem Jordan': ROLE_BOWLER,
    'C Hemraj': ROLE_BATTER,
    'CH Gayle': ROLE_BATTER,
    'CK Holder': ROLE_BOWLER,
    'CR Brathwaite': ROLE_BOWL_AR,
    'D Bishoo': ROLE_BOWLER,
    'DC Drakes': ROLE_BOWLER,
    'FA Allen': ROLE_BOWL_AR,
    'HR Walsh': ROLE_BOWLER,
    'J Blades': ROLE_BATTER,
    'JD Campbell': ROLE_BATTER,
    'JE Taylor': ROLE_BOWLER,
    'JL Carter': ROLE_BATTER,
    'JN Mohammed': ROLE_BATTER,
    'JO Holder': ROLE_BOWL_AR,
    'K Sinclair': ROLE_BOWLER,
    'KA Pollard': ROLE_BAT_AR,
    'KAJ Roach': ROLE_BOWLER,
    'KAR Hodge': ROLE_BAT_AR,
    'KC Brathwaite': ROLE_BATTER,
    'KJ Harding': ROLE_BOWLER,
    'KMA Paul': ROLE_BOWL_AR,
    'KOK Williams': ROLE_BOWLER,
    'KR Mayers': ROLE_BAT_AR,
    'KU Carty': ROLE_BATTER,
    'MJ Mindley': ROLE_BOWLER,
    'ML Cummins': ROLE_BOWLER,
    'MN Samuels': ROLE_BATTER,
    'MW Forde': ROLE_BOWLER,
    'N Pooran': ROLE_BATTER,
    'NE Bonner': ROLE_BATTER,
    'NO Miller': ROLE_BOWLER,
    'OC McCoy': ROLE_BOWLER,
    'OF Smith': ROLE_BOWLER,
    'R Powell': ROLE_BATTER,
    'RA Reifer': ROLE_BOWL_AR,
    'RR Beaton': ROLE_BOWLER,
    'S Joseph': ROLE_BOWLER,
    'SE Rutherford': ROLE_BATTER,
    'SH Lewis': ROLE_BOWLER,
    'SJ Benn': ROLE_BOWLER,
    'SK Springer': ROLE_BOWL_AR,
    'SP Narine': ROLE_BOWLER,
    'SS Cottrell': ROLE_BOWLER,
    'ST Gabriel': ROLE_BOWLER,
    'V Permaul': ROLE_BOWLER,
    'Y Cariah': ROLE_BOWLER,

    # --- BANGLADESH ---
    'Taskin Ahmed': ROLE_BOWLER,
    'Hasan Mahmud': ROLE_BOWLER,
    'Ebadot Hossain': ROLE_BOWLER,
    'Tanzim Hasan Sakib': ROLE_BOWLER,
    'Mustafizur Rahman': ROLE_BOWLER,
    'Shoriful Islam': ROLE_BOWLER,
    'Shakib Al Hasan': ROLE_BOWL_AR,
    'Nasum Ahmed': ROLE_BOWLER,
    'Taijul Islam': ROLE_BOWLER,
    'Mehedi Hasan Miraz': ROLE_BOWL_AR,
    'Rishad Hossain': ROLE_BOWLER,
    'Afif Hossain': ROLE_BAT_AR,
    'Anamul Haque': ROLE_BATTER,
    'Litton Das': ROLE_BATTER,
    'Mahmudullah': ROLE_BAT_AR,
    'Mahedi Hasan': ROLE_BOWL_AR,
    'Mashrafe Mortaza': ROLE_BOWLER,
    'Mehidy Hasan Miraz': ROLE_BOWL_AR,
    'Mohammad Saifuddin': ROLE_BOWL_AR,
    'Mosaddek Hossain': ROLE_BAT_AR,
    'Mushfiqur Rahim': ROLE_BATTER,
    'Nayeem Hasan': ROLE_BOWLER,
    'Rubel Hossain': ROLE_BOWLER,
    'Soumya Sarkar': ROLE_BAT_AR,
    'Sunzamul Islam': ROLE_BOWLER,

    # --- AFGHANISTAN ---
    'Azmatullah Omarzai': ROLE_BOWL_AR,
    'Fareed Ahmad': ROLE_BOWLER,
    'Fazalhaq Farooqi': ROLE_BOWLER,
    'Gulbadin Naib': ROLE_BOWL_AR,
    'Mohammad Nabi': ROLE_BOWL_AR,
    'Mujeeb Ur Rahman': ROLE_BOWLER,
    'Naveen-ul-Haq': ROLE_BOWLER,
    'Noor Ahmad': ROLE_BOWLER,
    'Qais Ahmad': ROLE_BOWLER,
    'Rashid Khan': ROLE_BOWL_AR,
    'AM Ghazanfar': ROLE_BOWLER,
    'Hamid Hassan': ROLE_BOWLER,
    'Izatullah Dawlatzai': ROLE_BOWLER,
    'Karim Janat': ROLE_BOWL_AR,
    'Mirwais Ashraf': ROLE_BOWL_AR,
    'Mohammad Shahzad': ROLE_BATTER,
    'Najibullah Zadran': ROLE_BATTER,
    'Nangeyalia Kharote': ROLE_BOWL_AR,
    'Samiullah Shinwari': ROLE_BAT_AR,
    'Sharafuddin Ashraf': ROLE_BOWL_AR,
    'Yamin Ahmadzai': ROLE_BOWLER,

    # --- ZIMBABWE ---
    'A Ndlovu': ROLE_BOWLER,
    'B Evans': ROLE_BOWL_AR,
    'B Madande': ROLE_BATTER,
    'B Muzarabani': ROLE_BOWLER,
    'BB Chari': ROLE_BATTER,
    'CJ Chibhabha': ROLE_BAT_AR,
    'CR Ervine': ROLE_BATTER,
    'CT Mumba': ROLE_BOWLER,
    'DT Tiripano': ROLE_BOWL_AR,
    'F Akram': ROLE_BOWLER,
    'H Masakadza': ROLE_BATTER,
    'Innocent Kaia': ROLE_BATTER,
    'J Gumbie': ROLE_BATTER,
    'KM Jarvis': ROLE_BOWLER,
    'LM Jongwe': ROLE_BOWL_AR,
    'M Shumba': ROLE_BAT_AR,
    'N Madziva': ROLE_BOWL_AR,
    'R Burl': ROLE_BAT_AR,
    'R Chakabva': ROLE_BATTER,
    'R Ngarava': ROLE_BOWLER,
    'SC Williams': ROLE_BAT_AR,
    'Sikandar Raza': ROLE_BOWL_AR,
    'T Maruma': ROLE_BATTER,
    'TL Chatara': ROLE_BOWLER,
    'TS Chisoro': ROLE_BOWLER,
    'V Sibanda': ROLE_BATTER,
    'WP Masakadza': ROLE_BOWLER,

    # --- IRELAND ---
    'AR McBrine': ROLE_BOWL_AR,
    'B McCarthy': ROLE_BOWLER,
    'C Campher': ROLE_BOWL_AR,
    'CA Young': ROLE_BOWLER,
    'F Hand': ROLE_BOWL_AR,
    'G Hume': ROLE_BOWLER,
    'GH Dockrell': ROLE_BAT_AR,
    'GJ Delany': ROLE_BAT_AR,
    'Harry Tector': ROLE_BATTER,
    'Joshua Little': ROLE_BOWLER,
    'L Tucker': ROLE_BATTER,
    'MR Adair': ROLE_BOWL_AR,
    'PR Stirling': ROLE_BATTER,
    'SC Getkate': ROLE_BOWL_AR,
    'Simi Singh': ROLE_BOWL_AR,
    'WB Rankin': ROLE_BOWLER,

    # --- NETHERLANDS ---
    'Aryan Dutt': ROLE_BOWLER,
    'Bas de Leede': ROLE_BOWL_AR,
    'Brandon Glover': ROLE_BOWLER,
    'Fred Klaassen': ROLE_BOWLER,
    'Logan van Beek': ROLE_BOWL_AR,
    'Max O\'Dowd': ROLE_BATTER,
    'Paul van Meekeren': ROLE_BOWLER,
    'Roelof van der Merwe': ROLE_BOWL_AR,
    'Ryan Klein': ROLE_BOWLER,
    'SA Engelbrecht': ROLE_BATTER,
    'Scott Edwards': ROLE_BATTER,
    'Shariz Ahmad': ROLE_BOWLER,
    'Sikander Zulfiqar': ROLE_BOWL_AR,
    'Tim Pringle': ROLE_BOWLER,
    'Vivian Kingma': ROLE_BOWLER,
    'Vikramjit Singh': ROLE_BATTER,
}